### ISSUE TITLE
Cloudflare Terraform provider crash: incorrect include rule type "github" (API returns "github-organization")

### ISSUE THREAD

**Issue by trapped** [cloudflare/terraform-provider-cloudflare#1075]
Currently using the Cloudflare provider v2.20.0.

Configuring an Access Group Policy to include a GitHub org's members:

- fails if applied with terraform (dashboard reports: `There is an error with one or more of your rules. Reconfigure by selecting an invalid rule and try again.` and deletes the include rule); Terraform configuration:

```tf
resource "cloudflare_access_group" "<stripped>" {
  account_id = var.cloudflare_account_id
  name       = "<stripped>"

  include {
    github {
      identity_provider_id = cloudflare_access_identity_provider.github.id
      name                 = "<stripped>"
    }
  }
}
```

- succeeds if applied from dashboard but crashes the Terraform provider; log/stack trace:

```
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: HTTP/2.0 200 OK
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Cf-Cache-Status: DYNAMIC
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Cf-Ray: 654d92a23aafff48-MAD
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Cf-Request-Id: 0a4459f95f0000ff48e33d0000000001
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Content-Security-Policy: frame-ancestors 'none'; default-src https: 'unsafe-inline'
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Content-Type: application/json; charset=UTF-8
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Date: Tue, 25 May 2021 09:00:21 GMT
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Server: cloudflare
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Strict-Transport-Security: max-age=31536000; includeSubDomains
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: Vary: Accept-Encoding
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: X-Content-Type-Options: nosniff
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: X-Envoy-Upstream-Service-Time: 13
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: X-Frame-Options: DENY
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: X-Xss-Protection: 1; mode=block
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: {
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:   "result": {
2021-05-25T11:00:21.169+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "id": "<stripped>",
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "name": "<stripped>",
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "uid": "<stripped>",
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "include": [
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:       {
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:         "github-organization": {
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:           "id": "<stripped>",
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:           "name": "<stripped>",
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:           "identity_provider_id": "<stripped>"
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:         }
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:       }
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     ],
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "require": [],
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "exclude": [],
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "created_at": "2021-05-25T08:42:57Z",
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:     "updated_at": "2021-05-25T08:56:13Z"
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:   },
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:   "success": true,
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:   "errors": [],
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0:   "messages": []
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: }
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 
2021-05-25T11:00:21.170+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: -----------------------------------------------------
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: PANIC: interface conversion: interface {} is nil, not string
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: goroutine 43 [running]:
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.TransformAccessGroupForSchema(0xc0002943c0, 0x1, 0x4, 0x1082700, 0xc0006b0828, 0x0)
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:615 +0x50e5
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupRead(0xc00084efc0, 0x12520e0, 0xc0004b6180, 0xc00084efc0, 0x0)
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:269 +0x91f
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000305320, 0xc0006c7220, 0x12520e0, 0xc0004b6180, 0xc0002c6130, 0x0, 0x0)
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource.go:460 +0x12e
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0003202b0, 0x1461bd0, 0xc0001173b0, 0xc00007c8a0, 0xc0003202b0, 0xc0001173b0, 0xc00009bba0)
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1212320, 0xc0003202b0, 0x1461bd0, 0xc0001173b0, 0xc00007c840, 0x0, 0x1461bd0, 0xc0001173b0, 0xc0000b22c0, 0xb0)
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000201c0, 0x146beb8, 0xc00030b500, 0xc0005fe100, 0xc0004a2f60, 0x1ab1d90, 0x0, 0x0, 0x0)
2021-05-25T11:00:21.171+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	google.golang.org/grpc@v1.31.1/server.go:1180 +0x52b
2021-05-25T11:00:21.172+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: google.golang.org/grpc.(*Server).handleStream(0xc0000201c0, 0x146beb8, 0xc00030b500, 0xc0005fe100, 0x0)
2021-05-25T11:00:21.172+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	google.golang.org/grpc@v1.31.1/server.go:1503 +0xd0c
2021-05-25T11:00:21.172+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00064c1a0, 0xc0000201c0, 0x146beb8, 0xc00030b500, 0xc0005fe100)
2021-05-25T11:00:21.172+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	google.golang.org/grpc@v1.31.1/server.go:843 +0xab
2021-05-25T11:00:21.172+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-05-25T11:00:21.172+0200 [DEBUG] provider.terraform-provider-cloudflare_v2.20.0: 	google.golang.org/grpc@v1.31.1/server.go:841 +0x1fd
2021-05-25T11:00:21.174+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/2.20.0/linux_amd64/terraform-provider-cloudflare_v2.20.0 pid=175807 error="exit status 2"
```

A quick skim of the source code at the top of the stack trace hints at a wrong schema field definition in the following file:

https://github.com/cloudflare/terraform-provider-cloudflare/blob/2a9594207b37c976d997e537ab449bbeb326d297/cloudflare/resource_cloudflare_access_group.go#L151

(specifies `github` instead of `github-organization`, which is what the API returns; I'm assuming the API)

**Comment by gstotts** [comment]
Looks like this case statement maybe in incorrrect:
https://github.com/cloudflare/terraform-provider-cloudflare/blob/2a9594207b37c976d997e537ab449bbeb326d297/cloudflare/resource_cloudflare_access_group.go#L616-L620

**Comment by jacobbednarz** [comment]
i mentioned it in the PR but will bring it here for posterity too.

i'm hesitant to accept this as we have already swapped this once in the past via #928 due to github-organization causing panics. can you provide a test case that asserts this should be correct?

**Comment by Justin-Holmes** [comment]
After testing, the `github` rule appears to be working correctly. My guess there was a panic causing bug that was resolved in a later release. I think this issue can be closed.

**Comment by jacobbednarz** [comment]
happy to revisit if we can get an updated issue. thanks @Justin-Holmes!
