### ISSUE TITLE
Crashes on cloudflare_notification_policy

### ISSUE THREAD

**Issue by abruyelles** [cloudflare/terraform-provider-cloudflare#1189]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.26.1

### Affected resource(s)

cloudflare_notification_policy

### Terraform configuration files

```hcl
resource cloudflare_notification_policy notif {
	account_id = var.account_id
	name = "Pool enablement"
	description = "Pool enablement"
	enabled     =  true
	alert_type  = "g6_pool_toggle_alert"

	email_integration {
		id   =  "myemail@example.com"
	}
	filters = {
		enabled = ["true", "false"]
	}
}
```

### Debug output

[log.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/7152993/log.txt)

### Expected output

I expect the ressource to be created without crashing terraform

### Actual output

Plugin crashes

### Steps to reproduce

1. Copy the configuration
2. Run terraform apply

**Comment by fabiosammy** [comment]
Still having this issue, more information about it (just for using the `filters` resource):

Terraform version: ``

<details>
```
Stack trace from the terraform-provider-cloudflare_v3.7.0 plugin:

panic: Unknown validation type: 6

goroutine 73 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.validateMapValues({0xd1efdb, 0x7}, 0xc00064cfe0, 0xc000403b80, {0xc00064cf60, 0x1, 0x1})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1912 +0x969
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateMap(0xc27820, {0xd1efdb, 0x7}, {0xc27820, 0xc000638c00}, 0x8bbfac, 0xc0006432e8, {0xc00064cf60, 0x1, 0x1})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1819 +0x271
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateType(0xc00064cde0, {0xd1efdb, 0x7f2d6a}, {0xc27820, 0xc000638c00}, 0xc000403b80, 0xc158c0, {0xc00064cf60, 0x1, 0x1})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:2111 +0x185
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validate(0xc46d00, {0xd1efdb, 0x7}, 0xc000403b80, 0xc000643708, {0xc00064cf60, 0x1, 0x1})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1534 +0x71a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateObject(0xc000638c60, {0x0, 0xc000634210}, 0xcf7120, 0xc00064c8d0, {0x13ca548, 0xc27820, 0xc000638b40})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1970 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Validate(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:649
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Validate(0xc0003ef260, 0xc0003d0300)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:542 +0x4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ValidateResource(0xe4cd60, {0xc00052e140, 0x1e}, 0xc000638b40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:254 +0xf2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ValidateResourceTypeConfig(0xc000320120, {0xc00063a1c0, 0xd1d11f}, 0xc0006341b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:230 +0x126
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ValidateResourceTypeConfig(0xc000322880, {0xe4c660, 0xc000638000}, 0xc00063a000)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:503 +0x2e2
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ValidateResourceTypeConfig_Handler({0xcede60, 0xc000322880}, {0xe4c660, 0xc000638000}, 0xc000636000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:272 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003388c0, {0xe5ae28, 0xc00049a000}, 0xc00053cc60, 0xc000451380, 0x138b2b0, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0003388c0, {0xe5ae28, 0xc00049a000}, 0xc00053cc60, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.40.0/server.go:939 +0x294

Error: The terraform-provider-cloudflare_v3.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

╷
│ Error: Plugin did not respond
│ 
│   with cloudflare_zone.service,
│   on zones.tf line 17, in resource "cloudflare_zone" "service":
│   17: resource "cloudflare_zone" "service" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
ERRO[0031] 1 error occurred:
	* exit status 1

```
</details>

**Comment by jacobbednarz** [comment]
@abruyelles can you please provide the full output of TF_LOG=DEBUG (not truncated, just sensitive data redacted) to assist with where this crash is occurring?

**Comment by abruyelles** [comment]
@jacobbednarz  Yes, here is the output from 3.8.0:
[log.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/7977004/log.txt)

**Comment by 0gajun** [comment]
@jacobbednarz 

Hi, I've tried to fix this issue and opened PR #1520 !

But, I couldn't find the document about `filter` attribute like https://github.com/cloudflare/terraform-provider-cloudflare/issues/1406 , so the PR only supports `zone` and `services` filters.

I think that there are more filters and we need to add support for additional filters.
Could you provide information about the filters in that PR?

**Comment by nikuljain** [comment]
We see the same issue on v3.35 also
