### ISSUE TITLE
registering SRV DNS record gives error

### ISSUE THREAD

**Issue by danforceDJ** [cloudflare/terraform-provider-cloudflare#1244]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform-provider-cloudflare_v3.1.0

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7" {
  allow_overwrite = false
  name = "_sipfederationtls._tcp"
  proxied = false
  ttl = 3600
  type = "SRV"
  zone_id = "b6fa9f7048d914ac79ad7ce3d9975182"
  data {
    name = "iute.ee"
    port = 5061
    priority = 100
    proto = "_tcp"
    service = "_sipfederationtls"
    target = "sipfed.online.lync.com"
    weight = 1
  }
}
```

### Debug output

{
 "result": {
  "id": "32a84f5fec535ab2199f8cc8f2b61ba7",
  "zone_id": "b6fa9f7048d914ac79ad7ce3d9975182",
  "zone_name": "iute.ee",
  "name": "_sipfederationtls._tcp.iute.ee",
  "type": "SRV",
  "content": "1\t5061\tsipfed.online.lync.com",
  "priority": 100,
  "proxiable": false,
  "proxied": false,
  "ttl": 3600,
  "locked": false,
  "data": {
   "name": "iute.ee",
   "port": 5061,
   "priority": 100,
   "proto": "_tcp",
   "service": "_sipfederationtls",
   "target": "sipfed.online.lync.com",
   "weight": 1
  },
  "meta": {
   "auto_added": false,
   "managed_by_apps": false,
   "managed_by_argo_tunnel": false,
   "source": "primary"
  },
  "created_on": "2021-08-16T07:07:28.805236Z",
  "modified_on": "2021-08-16T07:07:28.805236Z"
 },
 "success": true,
 "errors": [],
 "messages": []
}
[debug.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/7325653/debug.log)

### Panic output

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_record.terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7 will be updated in-place
  ~ resource "cloudflare_record" "terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7" {
      + allow_overwrite = false
        id              = "32a84f5fec535ab2199f8cc8f2b61ba7"
        name            = "_sipfederationtls._tcp"
        # (11 unchanged attributes hidden)

      + data {
          + name     = "iute.ee"
          + port     = 5061
          + priority = 100
          + proto    = "_tcp"
          + service  = "_sipfederationtls"
          + target   = "sipfed.online.lync.com"
          + weight   = 1
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│               
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_record.terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7: Modifying... [id=32a84f5fec535ab2199f8cc8f2b61ba7]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify that
│ no other changes are pending:
│     terraform plan
│       
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part
│ of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│   with cloudflare_record.terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7,
│   on iute.ee.tf line 110, in resource "cloudflare_record" "terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7":
│  110: resource "cloudflare_record" "terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-cloudflare_v3.1.0 plugin:

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 71 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareRecordUpdate(0xc00066cd00, {0x1bd9840, 0xc000826180})
        github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_record.go:510 +0xa39
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0002d8750, {0x1e04248, 0xc00010fdc0}, 0x24, {0x1bd9840, 0xc000826180})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:352 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001ee380, {0x1e04248, 0xc00010fdc0}, 0xc000918380, 0xc0003739c0, {0x1bd9840, 0xc000826180})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:464 +0x6ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000ac1e0, {0x1e04248, 0xc00010fdc0}, 0xc00088c320)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00007d8e0, {0x1e042f0, 0xc00079e060}, 0xc0005abc00)
        github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1b9c120, 0xc00007d8e0}, {0x1e042f0, 0xc00079e060}, 0xc00036c0c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003d8fc0, {0x1e15c28, 0xc0005c6000}, 0xc0000cd440, 0xc00024e660, 0x24b2f80, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0003d8fc0, {0x1e15c28, 0xc0005c6000}, 0xc0000cd440, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x294

Error: The terraform-provider-cloudflare_v3.1.0 plugin crashed!

### Expected output

applied succesfully

### Actual output

│ Error: Plugin did not respond
│ 
│   with cloudflare_record.terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7,
│   on iute.ee.tf line 110, in resource "cloudflare_record" "terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7":
│  110: resource "cloudflare_record" "terraform_managed_resource_32a84f5fec535ab2199f8cc8f2b61ba7" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

### Steps to reproduce

register SRV DNS

**Comment by jacobbednarz** [comment]
This looks like a duplicate of #1227. Can you please confirm you've tried the PR attached to it as a solution and it still doesn't work?
