### ISSUE TITLE
"Plugin did not respond" error when trying to import Access Group with "github" as the available type

### ISSUE THREAD

**Issue by marinkovicpetar** [cloudflare/terraform-provider-cloudflare#1494]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.9.1
```

### Affected resource(s)

`cloudflare_access_group`

### Terraform configuration files

```hcl
resource "cloudflare_access_group" "github" {
    account_id = "Cloudflare-Account-ID"
    name       = "Github"

    include {
        github {
            name                 = "Name-of-Github-Organization"
            identity_provider_id = "Github-Organization-Identity-ID"
        }
    }

    require {
        github {
            name                 = "Name-of-Github-Organization"
            identity_provider_id = "Github-Organization-Identity-ID"
        }
    }
}
```
```


### Debug output
2022-03-07T00:53:18.361+0100 [INFO]  Terraform version: 1.1.7
2022-03-07T00:53:18.362+0100 [INFO]  Go runtime version: go1.17.2
2022-03-07T00:53:18.362+0100 [INFO]  CLI args: []string{"C:\\dev\\terraform.exe", "import", "cloudflare_access_group.cloudflare_access_group_github", "<redacted>/<redacted>"}
2022-03-07T00:53:18.367+0100 [DEBUG] Attempting to open CLI config file: C:\Users\<redacted>\AppData\Roaming\terraform.rc
2022-03-07T00:53:18.367+0100 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2022-03-07T00:53:18.368+0100 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2022-03-07T00:53:18.370+0100 [DEBUG] ignoring non-existing provider search directory C:\Users\<redacted>\AppData\Roaming\terraform.d\plugins
2022-03-07T00:53:18.371+0100 [DEBUG] ignoring non-existing provider search directory C:\Users\<redacted>\AppData\Roaming\HashiCorp\Terraform\plugins
2022-03-07T00:53:18.371+0100 [INFO]  CLI command args: []string{"import", "cloudflare_access_group.cloudflare_access_group_github", "<redacted>/<redacted>"}
2022-03-07T00:53:18.434+0100 [DEBUG] checking for provisioner in "."
2022-03-07T00:53:18.434+0100 [DEBUG] checking for provisioner in "C:\\dev"
2022-03-07T00:53:19.900+0100 [DEBUG] Building and walking import graph
2022-03-07T00:53:19.900+0100 [DEBUG] ProviderTransformer: "cloudflare_access_group.cloudflare_access_group_github (import id \"<redacted>/<redacted>\")" (*terraform.graphNodeImportState) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2022-03-07T00:53:19.900+0100 [DEBUG] ProviderTransformer: "cloudflare_access_group.cloudflare_access_group_github" (*terraform.NodeAbstractResource) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2022-03-07T00:53:19.900+0100 [DEBUG] ProviderTransformer: "cloudflare_access_group.cloudflare_access_group_email_domain" (*terraform.NodeAbstractResource) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2022-03-07T00:53:19.901+0100 [DEBUG] ProviderTransformer: "cloudflare_access_group.cloudflare_access_group_emails" (*terraform.NodeAbstractResource) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2022-03-07T00:53:19.901+0100 [DEBUG] created provider logger: level=debug
2022-03-07T00:53:19.901+0100 [INFO]  provider: configuring client automatic mTLS
2022-03-07T00:53:19.914+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe args=[.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe]
2022-03-07T00:53:19.919+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe pid=19760
2022-03-07T00:53:19.919+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe
2022-03-07T00:53:19.946+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: configuring server automatic mTLS: timestamp=2022-03-07T00:53:19.944+0100
2022-03-07T00:53:19.960+0100 [DEBUG] provider: using plugin: version=5
2022-03-07T00:53:19.961+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: plugin address: network=tcp address=127.0.0.1:10000 timestamp=2022-03-07T00:53:19.960+0100
2022-03-07T00:53:19.996+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-03-07T00:53:20.007+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe pid=19760
2022-03-07T00:53:20.007+0100 [DEBUG] provider: plugin exited
2022-03-07T00:53:20.008+0100 [DEBUG] ReferenceTransformer: "cloudflare_access_group.cloudflare_access_group_email_domain" references: [var.account_id]
2022-03-07T00:53:20.008+0100 [DEBUG] ReferenceTransformer: "cloudflare_access_group.cloudflare_access_group_emails" references: [var.account_id]
2022-03-07T00:53:20.008+0100 [DEBUG] ReferenceTransformer: "var.account_id" references: []
2022-03-07T00:53:20.008+0100 [DEBUG] ReferenceTransformer: "cloudflare_access_group.cloudflare_access_group_github (import id \"<redacted>/<redacted>\")" references: []
2022-03-07T00:53:20.008+0100 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" references: []
2022-03-07T00:53:20.008+0100 [DEBUG] ReferenceTransformer: "cloudflare_access_group.cloudflare_access_group_github" references: [var.account_id]
2022-03-07T00:53:20.009+0100 [DEBUG] Starting graph walk: walkImport
2022-03-07T00:53:20.009+0100 [DEBUG] created provider logger: level=debug
2022-03-07T00:53:20.009+0100 [INFO]  provider: configuring client automatic mTLS
2022-03-07T00:53:20.020+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe args=[.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe]
2022-03-07T00:53:20.023+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe pid=14968
2022-03-07T00:53:20.023+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe
2022-03-07T00:53:20.044+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: configuring server automatic mTLS: timestamp=2022-03-07T00:53:20.043+0100
2022-03-07T00:53:20.054+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: plugin address: address=127.0.0.1:10000 network=tcp timestamp=2022-03-07T00:53:20.054+0100
2022-03-07T00:53:20.054+0100 [DEBUG] provider: using plugin: version=5
2022-03-07T00:53:20.091+0100 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" changed the config value, but that value is unused
2022-03-07T00:53:20.092+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: 2022/03/07 00:53:20 [INFO] Cloudflare Client configured for user:: timestamp=2022-03-07T00:53:20.092+0100
2022-03-07T00:53:20.092+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: 2022/03/07 00:53:20 [INFO] Using specified account id <redacted> in Cloudflare provider: timestamp=2022-03-07T00:53:20.092+0100
2022-03-07T00:53:20.092+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: 2022/03/07 00:53:20 [INFO] Cloudflare Client configured for user:: timestamp=2022-03-07T00:53:20.092+0100
2022-03-07T00:53:20.093+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: 2022/03/07 00:53:20 [DEBUG] Importing Cloudflare Access Group: accountID "<redacted>", accessGroupID "<redacted>": timestamp=2022-03-07T00:53:20.093+0100
2022-03-07T00:53:20.093+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: 2022/03/07 00:53:20 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/accounts/<redacted>/access/groups/<redacted> HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.1.7 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.9.1
Authorization: Bearer sBwpEnwBK7JE4mzJuJFkH7KG8etPai_4_ylFzKCv
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-03-07T00:53:20.093+0100
2022-03-07T00:53:21.529+0100 [INFO]  provider.terraform-provider-cloudflare_v3.9.1.exe: 2022/03/07 00:53:21 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6e7f029d590b278c-PRG
Content-Security-Policy: frame-ancestors 'none'; default-src https: 'unsafe-inline'
Content-Type: application/json; charset=UTF-8
Date: Sun, 06 Mar 2022 23:53:21 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU56Rb8iNWZVUvXhdaenCiDi5Mf; SameSite=Lax; path=/; expires=Mon, 07-Mar-22 02:23:22 GMT; HttpOnly
Set-Cookie: __cfruid=2f3544f77c8eb5dd704f32cfc5d389e5f9c0802d-1646610801; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Envoy-Upstream-Service-Time: 21
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{
  "result": {
    "id": "<redacted>",
    "name": "Github",
    "uid": "<redacted>",
    "include": [
      {
        "github-organization": {
          "id": "<redacted>",
          "name": "Github-Organization",
          "identity_provider_id": "<redacted>"
        }
      }
    ],
    "require": [
      {
        "github-organization": {
          "id": "<redacted>",
          "name": "Github-Organization",
          "identity_provider_id": "<redacted>"
        }
      }
    ],
    "exclude": [],
    "created_at": "2021-02-04T12:27:48Z",
    "updated_at": "2021-02-04T12:27:48Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}

-----------------------------------------------------: timestamp=2022-03-07T00:53:21.527+0100
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: panic: interface conversion: interface {} is nil, not string
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: goroutine 50 [running]:
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.TransformAccessGroupForSchema({0xc00030cb00, 0x1, 0x4})
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:422 +0x38bf
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupRead(0xc000216000, {0x1070920, 0xc0000f0780})
2022-03-07T00:53:21.531+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:52 +0x7b7
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupImport(0xc000216000, {0x1070920, 0xc0000f0780})
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:169 +0x2f9
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc000300660, {0x11aa5b8, 0xc000524f80}, 0xc000249a28, {0xc00030a1e0, 0x45})
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:384 +0x142
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc000304120, {0x11aa5b8, 0xc000524f80}, 0xc0002bd9c0)
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1043 +0xdf
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc00033c680, {0x11aa660, 0xc0007b6810}, 0xc0004f6eb0)
2022-03-07T00:53:21.532+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:628 +0x262
2022-03-07T00:53:21.533+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0x1044e80, 0xc00033c680}, {0x11aa660, 0xc0007b6810}, 0xc00078e300, 0x0)
2022-03-07T00:53:21.533+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x170
2022-03-07T00:53:21.533+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003288c0, {0x11b9448, 0xc000432ea0}, 0xc000230360, 0xc000455590, 0x16f3318, 0x0)
2022-03-07T00:53:21.533+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
2022-03-07T00:53:21.533+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: google.golang.org/grpc.(*Server).handleStream(0xc0003288c0, {0x11b9448, 0xc000432ea0}, 0xc000230360, 0x0)
2022-03-07T00:53:21.533+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
2022-03-07T00:53:21.534+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2022-03-07T00:53:21.534+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
2022-03-07T00:53:21.534+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-03-07T00:53:21.534+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.9.1.exe: 	google.golang.org/grpc@v1.44.0/server.go:919 +0x294
2022-03-07T00:53:21.539+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-03-07T00:53:21.539+0100 [ERROR] plugin.(*GRPCProvider).ImportResourceState: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-07T00:53:21.539+0100 [ERROR] vertex "cloudflare_access_group.cloudflare_access_group_github (import id \"<redacted>/<redacted>\")" error: Plugin did not respond
2022-03-07T00:53:21.569+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.9.1/windows_amd64/terraform-provider-cloudflare_v3.9.1.exe pid=14968 error="exit status 2"
2022-03-07T00:53:21.920+0100 [DEBUG] provider: plugin exited


### Panic output

_No response_

### Expected output

Resource is imported as other Access Group resources

### Actual output

cloudflare_access_group.cloudflare_access_group_github_lnzap: Importing from ID "<redacted>/<redacted>"...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-cloudflare_v3.9.1.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 50 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.TransformAccessGroupForSchema({0xc00030cb00, 0x1, 0x4})
        github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:422 +0x38bf
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupRead(0xc000216000, {0x1070920, 0xc0000f0780})
        github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:52 +0x7b7
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupImport(0xc000216000, {0x1070920, 0xc0000f0780})
        github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:169 +0x2f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc000300660, {0x11aa5b8, 0xc000524f80}, 0xc000249a28, {0xc00030a1e0, 0x45})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:384 +0x142
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc000304120, {0x11aa5b8, 0xc000524f80}, 0xc0002bd9c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1043 +0xdf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc00033c680, {0x11aa660, 0xc0007b6810}, 0xc0004f6eb0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:628 +0x262
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0x1044e80, 0xc00033c680}, {0x11aa660, 0xc0007b6810}, 0xc00078e300, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003288c0, {0x11b9448, 0xc000432ea0}, 0xc000230360, 0xc000455590, 0x16f3318, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0003288c0, {0x11b9448, 0xc000432ea0}, 0xc000230360, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-cloudflare_v3.9.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


### Steps to reproduce

1. Create `cloudflare_access_group" resource (per the settings already available in the UI)
2. Run `terraform import cloudflare_access_group.github cloudflare-account-id/access-group-id` (`access-group-id` of the present resource obtained via API call `curl -X GET "https://api.cloudflare.com/client/v4/accounts/<cloudflare-account-id>/access/groups .... `
3. Import fails



### Additional factoids

We're trying to import via Terraform our entire current configuration, completed manually in UI
Trying to import `cloudflare_access_group` resources with `email` or email-domain` in `include / require` block works just fine. Resource with `github` type is already in use, and I cannot recreate it, I am too afraid to broke current 40 access rules or something :)

### References

_No response_

**Comment by jaydeepappas1** [comment]
Can confirm, I am having the same issue with a "github" type access group. The error I see is slightly different, but largely the same: 

```
╷
│ Error: Request cancelled
│
│ The plugin.(*GRPCProvider).ImportResourceState request was cancelled.
╵


Stack trace from the terraform-provider-cloudflare_v3.9.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 22 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.TransformAccessGroupForSchema({0xc0001aa140, 0x1, 0x7})
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:422 +0x38bf
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupRead(0xc000092c00, {0x1930d00, 0xc000190480})
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:60 +0x8ec
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessGroupImport(0xc000092c00, {0x1930d00, 0xc000190480})
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_group.go:169 +0x2f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc000300660, {0x1a67738, 0xc0002287c0}, 0xc0001b3a28, {0xc000394000, 0x45})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:384 +0x142
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc0003340f0, {0x1a67738, 0xc0002287c0}, 0xc00014a3e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1043 +0xdf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc00033e780, {0x1a677e0, 0xc00008e420}, 0xc000136b40)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:628 +0x262
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0x19052e0, 0xc00033e780}, {0x1a677e0, 0xc00008e420}, 0xc00059e0c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003288c0, {0x1a76048, 0xc000433040}, 0xc000360000, 0xc0004455c0, 0x1fb4498, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0003288c0, {0x1a76048, 0xc000433040}, 0xc000360000, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-cloudflare_v3.9.1 plugin crashed!
```
