### ISSUE TITLE
Error: The terraform-provider-cloudflare_v3.14.0 plugin crashed!

### ISSUE THREAD

**Issue by andrewkrain** [cloudflare/terraform-provider-cloudflare#1610]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.1.9
Cloudflare provider 3.14.0

### Affected resource(s)

cloudflare_spectrum_application

### Terraform configuration files

```hcl
resource "cloudflare_spectrum_application" "endpoint" {
  for_each = {
    for endpoint in local.edge_endpoints : endpoint.name => endpoint
  }
  zone_id      = cloudflare_zone.main.id
  traffic_type = "direct"

  dns {
    type = each.value.edge.ips != null ? "ADDRESS" : "CNAME"
    name = each.value.edge.dns_name
  }
  edge_ip_connectivity = "all"
  edge_ips             = each.value.edge.ips
  protocol             = "tcp/${each.value.edge.port}"

  origin_dns {
    name = cloudflare_load_balancer.main.name
  }
  origin_port    = each.value.origin.port
  tls            = "off"
  ip_firewall    = false
  proxy_protocol = var.proxy_protocol ? "v2" : "off"
}
```

### Debug output

2022-05-10T16:32:50.492Z [INFO]  provider.terraform-provider-cloudflare_v3.11.0: 2022/05/10 16:32:50 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/zones/017e0312e7577130f17ca52d5bf08749/spectrum/apps/a6787f81343f4f1792d77c39bd972401 HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.1.9 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.11.0
Content-Type: application/json
X-Auth-Email: xxx
X-Auth-Key: xxx
Accept-Encoding: gzip

-----------------------------------------------------: timestamp=2022-05-10T16:32:50.492Z
2022-05-10T16:32:50.707Z [INFO]  provider.terraform-provider-cloudflare_v3.11.0: 2022/05/10 16:32:50 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cf-Cache-Status: DYNAMIC
Cf-Ray: 709412bbcd7526db-MSP
Content-Type: application/json; charset=UTF-8
Date: Tue, 10 May 2022 16:32:50 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZa4ACfsDBtGd; SameSite=Lax; path=/; expires=Tue, 10-May-22 19:02:51 GMT; HttpOnly
Set-Cookie: __cfruid=3caaba9eb5cace4011b08c2b1b72e9cab14484ca-1652200370; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 48

{
  "result": {
    "id": "a6787f81343f4f1792d77c39bd972401",
    "protocol": "tcp/80",
    "dns": {
      "type": "ADDRESS",
      "name": "xxx"
    },
    "origin_dns": {
      "name": "xxx"
    },
    "origin_port": 2080,
    "ip_firewall": false,
    "proxy_protocol": "v2",
    "tls": "off",
    "traffic_type": "direct",
    "edge_ips": {
      "type": "static",
      "ips": [
        "xxx",
"xxx"
      ]
    },
    "created_on": "2021-10-21T16:44:23.977388Z",
    "modified_on": "2021-10-21T16:44:23.977388Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}

-----------------------------------------------------: timestamp=2022-05-10T16:32:50.707Z
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: panic: runtime error: invalid memory address or nil pointer dereference
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5e3d9]
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: 
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: goroutine 356 [running]:
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareSpectrumApplicationRead(0xc0005bb180, {0xd5e100, 0xc0001e4840})
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_spectrum_application.go:116 +0xfb9
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xe9b8e0, {0xe9b8e0, 0xc0002136e0}, 0xd, {0xd5e100, 0xc0001e4840})
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:347 +0x178
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004ed0a0, {0xe9b8e0, 0xc0002136e0}, 0xc000845380, {0xd5e100, 0xc0001e4840})
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:650 +0x47b
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012f1b8, {0xe9b838, 0xc00038d100}, 0xc00038d180)
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:613 +0x534
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00017cb40, {0xe9b8e0, 0xc000213080}, 0xc000795260)
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:746 +0x48c
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd314e0, 0xc00017cb40}, {0xe9b8e0, 0xc000213080}, 0xc000795200, 0x0)
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001468c0, {0xeaa328, 0xc0003ac4e0}, 0xc000937e60, 0xc0004f4de0, 0x13fb370, 0x0)
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: google.golang.org/grpc.(*Server).handleStream(0xc0001468c0, {0xeaa328, 0xc0003ac4e0}, 0xc000937e60, 0x0)
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-05-10T16:32:50.710Z [DEBUG] provider.terraform-provider-cloudflare_v3.11.0:        google.golang.org/grpc@v1.45.0/server.go:919 +0x294
2022-05-10T16:32:50.714Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.11.0/linux_amd64/terraform-provider-cloudflare_v3.11.0 pid=297 error="exit status 2"
2022-05-10T16:32:50.714Z [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-05-10T16:32:50.714Z [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-05-10T16:32:50.714Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-05-10T16:32:50.714Z [ERROR] vertex "module.nessy.cloudflare_spectrum_application.endpoint[\"ep1:80\"]" error: Plugin did not respond
2022-05-10T16:32:50.714Z [ERROR] vertex "module.nessy.cloudflare_spectrum_application.endpoint[\"ep1:443\"]" error: Plugin did not respond
2022-05-10T16:32:50.714Z [ERROR] vertex "module.nessy.cloudflare_spectrum_application.endpoint" error: Plugin did not respond
2022-05-10T16:32:50.714Z [ERROR] vertex "module.nessy.cloudflare_spectrum_application.endpoint" error: Plugin did not respond
2022-05-10T16:32:50.714Z [ERROR] vertex "module.nessy.cloudflare_spectrum_application.endpoint (expand)" error: Plugin did not respond
2022-05-10T16:32:50.714Z [ERROR] vertex "module.nessy.cloudflare_spectrum_application.endpoint (expand)" error: Plugin did not respond
2022-05-10T16:32:50.717Z [INFO]  backend/local: plan operation completed
╷
│ Error: Plugin did not respond
│ 
│   with module.nessy.cloudflare_spectrum_application.endpoint["ep1:80"],
│   on ../../modules/proxy/main.tf line 105, in resource "cloudflare_spectrum_application" "endpoint":
│  105: resource "cloudflare_spectrum_application" "endpoint" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.nessy.cloudflare_spectrum_application.endpoint["ep1:443"],
│   on ../../modules/proxy/main.tf line 105, in resource "cloudflare_spectrum_application" "endpoint":
│  105: resource "cloudflare_spectrum_application" "endpoint" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-cloudflare_v3.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5e3d9]

goroutine 356 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareSpectrumApplicationRead(0xc0005bb180, {0xd5e100, 0xc0001e4840})
        github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_spectrum_application.go:116 +0xfb9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xe9b8e0, {0xe9b8e0, 0xc0002136e0}, 0xd, {0xd5e100, 0xc0001e4840})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:347 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004ed0a0, {0xe9b8e0, 0xc0002136e0}, 0xc000845380, {0xd5e100, 0xc0001e4840})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:650 +0x47b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012f1b8, {0xe9b838, 0xc00038d100}, 0xc00038d180)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:613 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00017cb40, {0xe9b8e0, 0xc000213080}, 0xc000795260)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd314e0, 0xc00017cb40}, {0xe9b8e0, 0xc000213080}, 0xc000795200, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001468c0, {0xeaa328, 0xc0003ac4e0}, 0xc000937e60, 0xc0004f4de0, 0x13fb370, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001468c0, {0xeaa328, 0xc0003ac4e0}, 0xc000937e60, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-cloudflare_v3.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

module.nessy.cloudflare_spectrum_application.endpoint["ep1:80"]: Refreshing state... [id=a6787f81343f4f1792d77c39bd972401]
module.nessy.cloudflare_spectrum_application.endpoint["ep1:443"]: Refreshing state... 

### Actual output

module.nessy.cloudflare_spectrum_application.endpoint["ep1:80"]: Refreshing state... [id=a6787f81343f4f1792d77c39bd972401]
module.nessy.cloudflare_spectrum_application.endpoint["ep1:443"]: Refreshing state... [id=f9b89defcc8c4b64afbfc5242ad04b61]
╷
│ Error: Request cancelled
│ 
│   with module.nessy.cloudflare_spectrum_application.endpoint["ep1:80"],
│   on ../../modules/proxy/main.tf line 105, in resource "cloudflare_spectrum_application" "endpoint":
│  105: resource "cloudflare_spectrum_application" "endpoint" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.nessy.cloudflare_spectrum_application.endpoint["ep1:443"],
│   on ../../modules/proxy/main.tf line 105, in resource "cloudflare_spectrum_application" "endpoint":
│  105: resource "cloudflare_spectrum_application" "endpoint" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

### Steps to reproduce

Use Cloudflare provider version 3.11.0 or newer and configure cloudflare_spectrum_application with [BYOIP](https://developers.cloudflare.com/spectrum/getting-started/byoip/)

### Additional factoids

This error appeared after upgrading Cloudflare provider to version 3.11.0 or newer

**Comment by andrewkrain** [comment]
In addition, now it wants to update cloudflare_spectrum_application on every run changing the order of static IPs:

```
# module.nessy.cloudflare_spectrum_application.endpoint["ep1:80"] will be updated in-place
  ~ resource "cloudflare_spectrum_application" "endpoint" {
      ~ edge_ips             = [
          - "xxx",
            "yyy",
          + "xxx",
        ]
        id                   = "d2b8fd70d54f4ac596be87dffd44f504"
        # (9 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # module.nessy.cloudflare_spectrum_application.endpoint["ep1:443"] will be updated in-place
  ~ resource "cloudflare_spectrum_application" "endpoint" {
      ~ edge_ips             = [
          - "xxx",
            "yyy",
          + "xxx",
        ]
        id                   = "bb309dfb1ac84f1b8baae8682b0fd091"
        # (9 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }
```

**Comment by jacobbednarz** [comment]
the `Read` panic looks like it would have been addressed by #1599. can you pull the latest master branch locally, build a version of the provider and confirm?

re: the ordering issue, have you recently added one? does it flip/flop the ordering or have you provided it differently in the resource to what the API is returning?

in future, please include the *entire* TF_LOG=DEBUG output, it makes investigating these issues far easier with less back and forth.

**Comment by andrewkrain** [comment]
> the `Read` panic looks like it would have been addressed by #1599. can you pull the latest master branch locally, build a version of the provider and confirm?
Will do.
> re: the ordering issue, have you recently added one? does it flip/flop the ordering or have you provided it differently in the resource to what the API is returning?
It does not appear to flip-flop so it must be different ordering.  Ordering does not matter and the provider should not be trying to enforce it.
> in future, please include the _entire_ TF_LOG=DEBUG output, it makes investigating these issues far easier with less back and forth.
I did.

**Comment by jacobbednarz** [comment]
> It does not appear to flip-flop so it must be different ordering. The ordering does not matter and the provider should not be trying to enforce it.

what makes you say it shouldn't be taking ordering into account? i'm looking at the schema internally and at one point, it looks like ordering was important for priority (in which case, `TypeList` is appropriate). can you update your resource to match the ordering from the API? i can chat to some folks on the service team to see if this is still required before we make any changes.

> > in future, please include the _entire_ TF_LOG=DEBUG output, it makes investigating these issues far easier with less back and forth.
> 
> I did.

there is quite a bit of context missing (hence the automation flagging it as missing); we aren't just interested in the HTTP interactions as there are log lines before this that would also be helpful. in essence, everything after you run `TF_LOG=DEBUG terraform apply|plan` is what is being requested.

**Comment by andrewkrain** [comment]
> > It does not appear to flip-flop so it must be different ordering. The ordering does not matter and the provider should not be trying to enforce it.
> 
> what makes you say it shouldn't be taking ordering into account? i'm looking at the schema internally and at one point, it looks like ordering was important for priority (in which case, `TypeList` is appropriate). can you update your resource to match the ordering from the API? i can chat to some folks on the service team to see if this is still required before we make any changes.

If the ordering is important, then why does not it "stick" after the provider updates it?
> > > in future, please include the _entire_ TF_LOG=DEBUG output, it makes investigating these issues far easier with less back and forth.
> > 
> > I did.
> 
> there is quite a bit of context missing (hence the automation flagging it as missing); we aren't just interested in the HTTP interactions as there are log lines before this that would also be helpful. in essence, everything after you run `TF_LOG=DEBUG terraform apply|plan` is what is being requested.

I did include all the output.

**Comment by andrewkrain** [comment]
Noticed that the issue is in [pending-op-response](https://github.com/cloudflare/terraform-provider-cloudflare/labels/workflow%2Fpending-op-response)

**Comment by andrewkrain** [comment]
@jacobbednarz - can you please reset the status?

**Comment by andrewkrain** [comment]
> the `Read` panic looks like it would have been addressed by #1599. can you pull the latest master branch locally, build a version of the provider and confirm?

Confirmed the issue is addressed in 3.15.0
> re: the ordering issue, have you recently added one? does it flip/flop the ordering or have you provided it differently in the resource to what the API is returning?

I re-tested and it indeed simply flip/flops regardless of which order you provide the IPs.

**Comment by amitsrivastavaswissre** [comment]
This is a really weird issue , can you please help us. I am getting this issue now:
Error: The terraform-provider-cloudflare_v3.15.0 plugin crashed!

We have enable TF_Log , but not getting much information. We are running Terraform in Azure DevOps and deploying some cloudflare stuff. 

Below is our configuration details:
terraform {
  required_version = ">= 1.1.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.76.0"
    }
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "3.15.0"
    }
  }
  backend "azurerm" {}
}

**Comment by amitsrivastavaswissre** [comment]
issue is as shown below:

	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014a8c0, {0xf26ac0, 0xc0003f7a00}, 0xc000527440, 0xc0003ff290, 0x14282f0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00014a8c0, {0xf26ac0, 0xc0003f7a00}, 0xc000527440, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-cloudflare_v3.15.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by amitsrivastavaswissre** [comment]
I think this issue is not resolved in 3.15.0

**Comment by jcquiles** [comment]
I have the same error happening, is this still unresolved or is there another solution worth a try?

`Error: The terraform-provider-cloudflare_v3.17.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by andrewkrain** [comment]
> I think this issue is not resolved in 3.15.0

For us upgrading to 3.15.0 resolved the issue with plugin crashing, however, the issue with sorting flip-flopping is still present.

What is really frustrating is the issue is still in mislabeled with [pending-op-response](https://github.com/cloudflare/terraform-provider-cloudflare/labels/workflow%2Fpending-op-response) status and @jacobbednarz is incommunicado.

**Comment by andrewkrain** [comment]
Upgraded to 3.19.0 and TF to 1.2.5 and confirmed that the issue with sorting flip-flopping is still present.

@jacobbednarz - do you realize that it is unprofessional and rude to ignore comments and questions, especially when done repeatedly?

**Comment by garrettgalow** [comment]
I removed the label. Sounds the remaining issue has been identified, and it comes down to when this gets prioritized to be fixed. Right now there isn't an ETA for that.

**Comment by andrewkrain** [comment]
@garrettgalow - what is the priority and ETA on this considering we are an enterprise customer and this issue was reported half a year ago? 

To recap, the provider since version 3.14 is trying to enforce the order of static IPs for Spectrum Apps to the opposite of the order returned by the API and saved in the state file. This results of hundreds of unnecessary updates on every Terraform run and plan output that our team has to review during every deployment.  Not only this is a major time waste, but it makes the review process prone to error as it is very easy to miss unintended changes hidden among the 382 bogus changes caused by this bug.

**Comment by garrettgalow** [comment]
The issue has been escalated to the spectrum team internally to investigate, but they are still investigating the issue
