### ISSUE TITLE
[cache_key_fields] panic: interface conversion: interface {} is nil, not map[string]interface

### ISSUE THREAD

**Issue by Kevin-Li-Webjet** [cloudflare/terraform-provider-cloudflare#2062]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform: 1.3.5
Cloudflare plugin: 3.28.0 

### Affected resource(s)

cloudflare_page_rule -> cache_key_fields

### Terraform configuration files

```hcl
resource "cloudflare_page_rule" "page_rule_4086xxxf46f9" {
    zone_id = var.zone_id

    target = "www.example.com/*"

    priority = 6
    status = "active"
    actions {
    
        cache_level = "cache_everything"
    
        edge_cache_ttl = 18000
    
        cache_key_fields {
            query_string {
                exclude = ["a_xxx","b_xxx","c_tid","d_xxxx","e_xxx","f_xxx","fbclid","xid","xhash","msclkid","dclid","gclid"]
            }
            header {
                include = ["authorization"]
            }
            cookie {}
            user {}
            host {}
        }
    }
    depends_on = [cloudflare_page_rule.page_rule_d82xxxxx6c5f4e1]
}
```

### Link to debug output

https://gist.github.com/Kevin-Li-Webjet/50f85989088e63464f7ef176072fcd08

### Panic output

Stack trace from the terraform-provider-cloudflare_v3.28.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 43 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/provider.transformToCloudflarePageRuleAction({0x10360c8, 0xc0005248a0}, {0xebcf3a, 0x10}, {0xd46900?, 0xc0005f2048?}, 0x8?)
        github.com/cloudflare/terraform-provider-cloudflare/internal/provider/resource_cloudflare_page_rule.go:466 +0x11f7
github.com/cloudflare/terraform-provider-cloudflare/internal/provider.resourceCloudflarePageRuleUpdate({0x10360c8, 0xc0005248a0}, 0xc000582780, {0xeae680?, 0xc0000c03c0?})
        github.com/cloudflare/terraform-provider-cloudflare/internal/provider/resource_cloudflare_page_rule.go:176 +0x6fa
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00016eb60, {0x1036100, 0xc0004b5a70}, 0xd?, {0xeae680, 0xc0000c03c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00016eb60, {0x1036100, 0xc0004b5a70}, 0xc000393040, 0xc0000ad200, {0xeae680, 0xc0000c03c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010078, {0x1036100?, 0xc0004b51d0?}, 0xc0000b0460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000256a00, {0x1036100?, 0xc000186630?}, 0xc000258310)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe7dfe0?, 0xc000256a00}, {0x1036100, 0xc000186630}, 0xc000258070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ae000, {0x1039d00, 0xc0004f8680}, 0xc00033e000, 0xc0003038c0, 0x1599120, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0004ae000, {0x1039d00, 0xc0004f8680}, 0xc00033e000, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v3.28.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

changes applied

### Actual output

 Error: Plugin did not respond
│ 
│   with module.xxxx.cloudflare_page_rule.page_rule_63896b0561214cbeb2ec384bf2ef36a0,
│   on accounts/xxxx/xxxx/page_rules.tf line 229, in resource "cloudflare_page_rule" "page_rule_63896b056xxxx4bf2ef36a0":
│  229: resource "cloudflare_page_rule" "page_rule_63896b056xxxxx4bf2ef36a0" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs
│ may contain more details.

### Steps to reproduce

take my config code
terraform init
terraform plan
terraform apply

### References

similar with https://github.com/hashicorp/terraform-provider-aws/issues/24881

**Comment by Kevin-Li-Webjet** [comment]
2022-11-29T22:37:25.110Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: cache_key_fields action to be applied: []interface {}{map[string]interface {}{"cookie":[]interface {}{map[string]interface {}{"check_presence":*Set(map[string]interface {}(nil)), "include":*Set(map[string]interface {}(nil))}}, "header":[]interface {}{map[string]interface {}{"check_presence":*Set(map[string]interface {}(nil)), "exclude":*Set(map[string]interface {}(nil)), "include":*Set(map[string]interface {}{"1405523147":"authorization"})}}, "host":[]interface {}{map[string]interface {}{"resolved":false}}, "query_string":[]interface {}{map[string]interface {}{"exclude":*Set(map[string]interface {}{"1427741591":"utm_term", "1758001918":"fbclid", "2018762823":"xid", "2052660961":"dclid", "2220716248":"utm_tid", "223125000":"utm_source", "2447139227":"utm_medium", "2850690849":"utm_content", "4241321039":"gclid", "566336536":"utm_campaign", "921918567":"xhash", "978681895":"msclkid"}), "ignore":false, "include":*Set(map[string]interface {}(nil))}}, "user":[]interface {}{interface {}(nil)}}}: timestamp=2022-11-29T22:37:25.110Z
2022-11-29T22:37:25.115Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: panic: interface conversion: interface {} is nil, not map[string]interface {}
2022-11-29T22:37:25.115Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: 
2022-11-29T22:37:25.115Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: goroutine 27 [running]:
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/cloudflare/terraform-provider-cloudflare/internal/provider.transformToCloudflarePageRuleAction({0x10360c8, 0xc0005576e0}, {0xebcf3a, 0x10}, {0xd46900?, 0xc0002eef48?}, 0x8?)
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/cloudflare/terraform-provider-cloudflare/internal/provider/resource_cloudflare_page_rule.go:466 +0x11f7
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/cloudflare/terraform-provider-cloudflare/internal/provider.resourceCloudflarePageRuleUpdate({0x10360c8, 0xc0005576e0}, 0xc000625300, {0xeae680?, 0xc000126600?})
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/cloudflare/terraform-provider-cloudflare/internal/provider/resource_cloudflare_page_rule.go:176 +0x6fa
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00018aa80, {0x1036100, 0xc000760d50}, 0xd?, {0xeae680, 0xc000126600})
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00018aa80, {0x1036100, 0xc000760d50}, 0xc0002bac30, 0xc000601600, {0xeae680, 0xc000126600})
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000462000, {0x1036100?, 0xc000760c30?}, 0xc000587360)
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000000b40, {0x1036100?, 0xc000259890?}, 0xc000606a10)
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
2022-11-29T22:37:25.116Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe7dfe0?, 0xc000000b40}, {0x1036100, 0xc000259890}, 0xc0006069a0, 0x0)
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000476000, {0x1039d00, 0xc0003189c0}, 0xc0001c6240, 0xc0003019b0, 0x1599120, 0x0)
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: google.golang.org/grpc.(*Server).handleStream(0xc000476000, {0x1039d00, 0xc0003189c0}, 0xc0001c6240, 0x0)
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-11-29T22:37:25.117Z [DEBUG] provider.terraform-provider-cloudflare_v3.28.0:        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
2022-11-29T22:37:25.126Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-11-29T22:37:25.126Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.28.0/linux_amd64/terraform-provider-cloudflare_v3.28.0 pid=30 error="exit status 2"
2022-11-29T22:37:25.127Z [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-11-29T22:37:25.139Z [ERROR] vertex "module.xxx.cloudflare_page_rule.page_rule_63896b0561xxxxf2ef36a0" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│ 
│   with module.xxx.cloudflare_page_rule.page_rule_63896b056xxxxb2ec384bf2ef36a0,
│   on accounts/xxx/xxx/page_rules.tf line 229, in resource "cloudflare_page_rule" "page_rule_63896b0561214cbeb2ec384bf2ef36a0":
│  229: resource "cloudflare_page_rule" "page_rule_63896b056121xxxxx384bf2ef36a0" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
2022-11-29T22:37:25.460Z [DEBUG] Azure Backend Request: 
HEAD /cloudflare/terraform.tfstate HTTP/1.1
Host: wjtfstates.blob.core.windows.net
User-Agent: HashiCorp Terraform/1.3.5 (+https://www.terraform.io)
X-Ms-Date: Tue, 29 Nov 2022 22:37:25 GMT
X-Ms-Lease-Id: 45f069c1-e955-c4fb-d9f9-a6b82171d6f8
X-Ms-Version: 2018-11-09
2022-11-29T22:37:25.480Z [DEBUG] Azure Backend Response for https://xxx.blob.core.windows.net/cloudflare/terraform.tfstate: 
HTTP/1.1 200 OK
Content-Length: 1300768

**Comment by jacobbednarz** [comment]
please supply the entirety of the TF_LOG=DEBUG output (in your gist), not just the truncated version as it is missing context.

**Comment by Kevin-Li-Webjet** [comment]
![image](https://user-images.githubusercontent.com/61395724/204668430-14205f98-c457-422d-b269-0b098d6545be.png)
looks like when "user" caused the panic, which doesn't accept empty as doc described (**_user - (Required, but allowed to be empty)_**)

I have pass value 
`user {device_type=false}`
now everything is working
