### ISSUE TITLE
cloudflare_waf_group read crash when API returns 502 error

### ISSUE THREAD

**Issue by camlow325** [cloudflare/terraform-provider-cloudflare#2209]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [ ] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.3.0
```

### Affected resource(s)

* cloudflare_waf_group

### Terraform configuration files

```hcl
resource "cloudflare_waf_group" "cloudflare_miscellaneous" {
  zone_id    = "..."
  package_id = "1e334..."
  group_id   = "da9d7..."
  mode       = "on"
}
```

### Debug output

Snippet for HTTP 502 just before crash:

```
GET /client/v4/zones/.../firewall/waf/packages/.../groups/... HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.0.8 terraform-plugin-sdk/2.8.0 terraform-provider-cloudflare/3.3.0
Authorization: Bearer ...
Content-Type: application/json
Accept-Encoding: gzip

-----------------------------------------------------: timestamp=2023-02-01T02:51:11.333Z
2023-02-01T02:51:11.464Z [INFO]  provider.terraform-provider-cloudflare_v3.3.0: 2023/02/01 02:51:11 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 502 Bad Gateway
Content-Length: 158
Cf-Cache-Status: DYNAMIC
Cf-Ray: ...
Content-Type: text/html
Date: Wed, 01 Feb 2023 02:51:11 GMT
Server: cloudflare
Set-Cookie: ...
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare-lb</center>
</body>
</html>
```

### Panic output

```
Stack trace from the terraform-provider-cloudflare_v3.3.0 plugin:

panic: interface conversion: error is *errors.fundamental, not *cloudflare.APIRequestError

goroutine 341 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareWAFGroupRead(0x68, {0xfe4c20, 0xc0001f20c0})
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_waf_group.go:63 +0x2ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xfe9458, {0x12110a8, 0xc000054180}, 0x24, {0xfe4c20, 0xc0001f20c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:335 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00056fce0, {0x12110a8, 0xc000054180}, 0xc000a489c0, {0xfe4c20, 0xc0001f20c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c360, {0x12110a8, 0xc000054180}, 0xc000055bc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000503420, {0x1211150, 0xc0003ed470}, 0xc000367980)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xfa6d80, 0xc000503420}, {0x1211150, 0xc0003ed470}, 0xc0003677a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005acfc0, {0x12229e8, 0xc000190600}, 0xc000afcea0, 0xc0006d7a10, 0x18bfe30, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0005acfc0, {0x12229e8, 0xc000190600}, 0xc000afcea0, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.40.0/server.go:939 +0x294

Error: The terraform-provider-cloudflare_v3.3.0 plugin crashed!
```

### Expected output

Apply successful

### Actual output

Apply failed with error:

```
Error: Plugin did not respond

  with cloudflare_waf_group.cloudflare_miscellaneous,
  on waf-cloudflare.tf line 1, in resource "cloudflare_waf_group" "cloudflare_miscellaneous":
  33: resource "cloudflare_waf_group" "cloudflare_miscellaneous" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-cloudflare_v3.3.0 plugin:

panic: interface conversion: error is *errors.fundamental, not *cloudflare.APIRequestError
...
```

Note that this was only a temporary error. Later applies were successful, after the API no longer was returning `502` errors.

### Steps to reproduce

1. Terraform apply

**Comment by jacobbednarz** [comment]
as this is a service error and this is for the legacy WAF, I'm going to close this off as we are unlikely to spend any effort on this one.
