### ISSUE TITLE
cloudflare_page_rule crashing provider

### ISSUE THREAD

**Issue by jordanfelle** [cloudflare/terraform-provider-cloudflare#2335]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.2.0
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Affected resource(s)

cloudflare_page_rule

### Terraform configuration files

```hcl
resource "cloudflare_page_rule" "rule" {
  zone_id  = cloudflare_zone.zone.id
  target   = "example.com/*"
  priority = 1
  status   = "active"

  actions {
    cache_level    = "cache_everything"
    edge_cache_ttl = 7200
    
    cache_key_fields {
      query_string {
        exclude = ["foo", "bar"]
      }
      user {}
      host {}
    }
  }
}
```

### Link to debug output

Unable to provide

### Panic output

```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-cloudflare_v4.2.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 129 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.transformToCloudflarePageRuleAction({0x118cf48, 0xc00040a6f0}, {0xfe3ed8, 0x10}, {0xe450e0?, 0xc0009204c8?}, 0xe38660?)
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_page_rule.go:487 +0x11bb
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflarePageRuleUpdate({0x118cf48, 0xc00040a6f0}, 0xc000551180, {0xfd4fa0?, 0xc00054ac00?})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_page_rule.go:177 +0x6b9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003bed20, {0x118cf80, 0xc000416d80}, 0xd?, {0xfd4fa0, 0xc00054ac00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003bed20, {0x118cf80, 0xc000416d80}, 0xc0000ba340, 0xc000674980, {0xfd4fa0, 0xc00054ac00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00012f278, {0x118cf80?, 0xc000416900?}, 0xc0002356d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1192c70?, 0xc00012f278?}}, {0x118cf80, 0xc000416900}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc0003f66c0, 0xc0003f6720, {0xc000531680, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00054f9a0, {0x118cf80?, 0xc0003f6c00?}, 0xc00019e070)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xfa5ac0?, 0xc00054f9a0}, {0x118cf80, 0xc0003f6c00}, 0xc00019e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b61e0, {0x1191c18, 0xc000102b60}, 0xc00048e000, 0xc00030f6b0, 0x177fe60, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0000b61e0, {0x1191c18, 0xc000102b60}, 0xc00048e000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v4.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected output

We should be able to add the cache key fields

### Actual output

Plugin crashes

### Steps to reproduce

Attempt to create a page rule with cache key fields and at least 1 of the required fields empty

**Comment by jfelle-tenable** [comment]
Provided output in support case

**Comment by jordanfelle** [comment]
Provided output in support case

**Comment by jacobbednarz** [comment]
using 4.2.0, i'm unable to replicate using the reproduction provided.

```
resource "cloudflare_page_rule" "rule" {
  zone_id  = "0da42c8d2132a9ddaf714f9e7c920711"
  target   = "terraform.cfapi.net/*"
  priority = 1
  status   = "active"

  actions {
    cache_level    = "cache_everything"
    edge_cache_ttl = 7200

    cache_key_fields {
      query_string {
        exclude = ["foo", "bar"]
      }
      host {}
      user {}
    }
  }
}
```

```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_page_rule.rule will be created
  + resource "cloudflare_page_rule" "rule" {
      + id       = (known after apply)
      + priority = 1
      + status   = "active"
      + target   = "terraform.cfapi.net/*"
      + zone_id  = "0da42c8d2132a9ddaf714f9e7c920711"

      + actions {
          + always_use_https    = false
          + cache_level         = "cache_everything"
          + disable_apps        = false
          + disable_performance = false
          + disable_railgun     = false
          + disable_security    = false
          + disable_zaraz       = false
          + edge_cache_ttl      = 7200

          + cache_key_fields {

              + host {
                  + resolved = false
                }

              + query_string {
                  + exclude = [
                      + "bar",
                      + "foo",
                    ]
                  + ignore  = (known after apply)
                  + include = (known after apply)
                }

              + user {
                  + device_type = (known after apply)
                  + geo         = (known after apply)
                  + lang        = (known after apply)
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_page_rule.rule: Creating...
cloudflare_page_rule.rule: Creation complete after 1s [id=36255c7ab9376f9dc10edfc12848ec52]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
and with subsequent operations
```
$ terraform apply
cloudflare_page_rule.rule: Refreshing state... [id=36255c7ab9376f9dc10edfc12848ec52]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

have you definitely been able to replicate this on 4.2.0 with a new resource?

**Comment by jacobbednarz** [comment]
as a side note, i recommend swapping to using `cloudflare_ruleset` to configure cache keys as that has recently been migrated to the terraform-plugin-framework and you get away from weird syntaxes like the empty `user` and `host` blocks.

**Comment by jordanfelle** [comment]
We are on the latest provider and TF and it still happens. We are trying to move to ruleset instead, but when we try to add a third rule to cache we get a 500 back from cloudflare. We have case 2751024 open

**Comment by jordanfelle** [comment]
For it to work we ended up having to add all options, so they should be set to required or have defaults set

```
    cache_key_fields {
      query_string {
        exclude = ["foo", "bar"]
      }
      user {
        device_type = false
        geo         = false
        lang        = false
      }
      host {
        resolved = false
      }
    }
  }
```

**Comment by jordanfelle** [comment]
And https://github.com/cloudflare/terraform-provider-cloudflare/issues/2360 is another blocker to move to the ruleset one for us :(

**Comment by lilHermit** [comment]
I'm hitting this issue too but with `cloudflare_teams_rule` I'm adding ZeroTrust to our EKS API Servers.

``` 
resource "cloudflare_teams_rule" "live_k8s_apiserver_zero_trust_http" {
  account_id  = local.cloudflare_dts_account_id
  name        = "Don't inspect Kubernetes API - Live"
  description = "Allow connections from kubectl to API - Live"
  precedence  = 10000
  action      = "off"
  enabled     = true
  filters     = ["http"]
  traffic     = format("any(http.conn.dst_ip[*] in $%s)", replace(cloudflare_teams_list.live_k8s_apiserver_ips.id, "-", ""))
  rule_settings {
  }
}
```

``` 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_teams_rule.live_k8s_apiserver_zero_trust_http: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v4.5.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 38 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.inflateTeamsRuleSettings({0xe5e940?, 0xc000697800?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:238 +0xe45
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTeamsRuleCreate({0x11b1408, 0xc00040a1e0}, 0x0?, {0xff2a00?, 0xc00055c000?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:86 +0xde
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003ab7a0, {0x11b1440, 0xc000b832c0}, 0xd?, {0xff2a00, 0xc00055c000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003ab7a0, {0x11b1440, 0xc000b832c0}, 0xc000523ad0, 0xc00053ca00, {0xff2a00, 0xc00055c000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000112c0, {0x11b1440?, 0xc000b830e0?}, 0xc00066a5a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x11b7190?, 0xc0000112c0?}}, {0x11b1440, 0xc000b830e0}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc0003baae0, 0xc0003bab40, {0xc000526de0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0004d30e0, {0x11b1440?, 0xc000b823c0?}, 0xc00018e5b0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xfc3180?, 0xc0004d30e0}, {0x11b1440, 0xc000b823c0}, 0xc00018e540, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ca5a0, {0x11b6118, 0xc0005009c0}, 0xc0002fcea0, 0xc0003ebbc0, 0x17b3380, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0004ca5a0, {0x11b6118, 0xc0005009c0}, 0xc0002fcea0, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-cloudflare_v4.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by lilHermit** [comment]
I worked around this by creating the resource (using bare minimum) in the console and then importing into TF
