### ISSUE TITLE
Crashes on cloudflare_notification_policy 

### ISSUE THREAD

**Issue by nikuljain** [cloudflare/terraform-provider-cloudflare#2410]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

latest

### Affected resource(s)

resource "cloudflare_notification_policy"

### Terraform configuration files

```hcl
resource "cloudflare_notification_policy" "default" {
  for_each   = var.cloudflare_notification_policy
  account_id = each.value.account_id
  name       = each.value.name
  enabled    = each.value.enabled
  alert_type = each.value.alert_type

  dynamic "email_integration" {
    for_each = each.value.email_integration
    content {
      id = email_integration.value.id
    }
  }

  filters {
    pool_id = coalesce(
      each.value.filters.pool_id,
      each.value.filter_by_pools && contains(["load_balancing_health_alert", "load_balancing_pool_enablement_alert"], lower(each.value.alert_type))
      ? [for k in keys(var.pools) : cloudflare_load_balancer_pool.default[k].id] : []
    )

    enabled             = each.value.filters.enabled
    event_source        = each.value.filters.event_source
    event_type          = each.value.filters.event_type
    health_check_id     = each.value.filters.health_check_id
    input_id            = each.value.filters.input_id
    limit               = each.value.filters.limit
    new_health          = each.value.filters.new_health
    packets_per_second  = each.value.filters.packets_per_second
    product             = each.value.filters.product
    protocol            = each.value.filters.protocol
    requests_per_second = each.value.filters.requests_per_second
    services            = each.value.filters.services
    slo                 = each.value.filters.slo
    status              = each.value.filters.status
    target_host         = each.value.filters.target_host
    target_zone_name    = each.value.filters.target_zone_name
    zones               = each.value.filters.zones
  }
}
```

### Link to debug output

NA

### Panic output

Error: Plugin did not respond
│ Warning: Attribute Deprecated
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on ci-tmp-provider.tf line 31, in provider "cloudflare":
│   31: 	account_id = var.cloudflare_account_id
│ 
│ Use resource specific `account_id` attributes instead.
╵

Stack trace from the terraform-provider-cloudflare_v3.33.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 84 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.expandNotificationPolicyFilter({0xc0008150c0, 0x1, 0xfbb692?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_notification_policy.go:180 +0x2c5
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildNotificationPolicy(0xc000730a70?)
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_notification_policy.go:171 +0x3a5
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareNotificationPolicyCreate({0x1171b88, 0xc0005806c0}, 0x0?, {0xfb6f40?, 0xc0000ade00?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_notification_policy.go:38 +0xcd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003f02a0, {0x1171bc0, 0xc000294750}, 0xd?, {0xfb6f40, 0xc0000ade00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003f02a0, {0x1171bc0, 0xc000294750}, 0xc00071ab[60](https://github.com/LexisNexis-RBA/ins-sreadmin-cloudflare-lb/actions/runs/4891972239/jobs/8733484850#step:10:61), 0xc00045f180, {0xfb6f40, 0xc0000ade00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010db0, {0x1171bc0?, 0xc000294540?}, 0xc0005[63](https://github.com/LexisNexis-RBA/ins-sreadmin-cloudflare-lb/actions/runs/4891972239/jobs/8733484850#step:10:64)d10)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1177310?, 0xc000010db0?}}, {0x1171bc0, 0xc000294540}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000448780, 0xc0004487e0, {0xc0004d9920, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00012aaa0, {0x1171bc0?, 0xc00047dcb0?}, 0xc0003dcaf0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xf885c0?, 0xc00012aaa0}, {0x1171bc0, 0xc00047dcb0}, 0xc0003dca80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000202000, {0x1176660, 0xc0000076c0}, 0xc000728b40, 0xc000199e90, 0x1743820, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000202000, {0x1176660, 0xc0000076c0}, 0xc000728b40, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:9[65](https://github.com/LexisNexis-RBA/ins-sreadmin-cloudflare-lb/actions/runs/4891972239/jobs/8733484850#step:10:66) +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v3.33.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2023-05-05T09:51:52Z level=error msg=Terraform invocation failed in /home/runner/work/ins-sreadmin-cloudflare-lb/ins-sreadmin-cloudflare-lb/.terragrunt-download/umK_vABaKPXKCXI1DazAvjCeyXo/T9h2p8m1HnkCZG2au-AxDdYVVvs prefix=[products/testhealth/ct] 
time=2023-05-05T09:51:52Z level=error msg=1 error occurred:
	* exit status 1

### Expected output

notification should get created

### Actual output

Error: Plugin did not respond
│ Warning: Attribute Deprecated
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on ci-tmp-provider.tf line 31, in provider "cloudflare":
│   31: 	account_id = var.cloudflare_account_id
│ 
│ Use resource specific `account_id` attributes instead.
╵

Stack trace from the terraform-provider-cloudflare_v3.33.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 84 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.expandNotificationPolicyFilter({0xc0008150c0, 0x1, 0xfbb692?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_notification_policy.go:180 +0x2c5
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildNotificationPolicy(0xc000730a70?)
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_notification_policy.go:171 +0x3a5
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareNotificationPolicyCreate({0x1171b88, 0xc0005806c0}, 0x0?, {0xfb6f40?, 0xc0000ade00?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_notification_policy.go:38 +0xcd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003f02a0, {0x1171bc0, 0xc000294750}, 0xd?, {0xfb6f40, 0xc0000ade00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003f02a0, {0x1171bc0, 0xc000294750}, 0xc00071ab[60](https://github.com/LexisNexis-RBA/ins-sreadmin-cloudflare-lb/actions/runs/4891972239/jobs/8733484850#step:10:61), 0xc00045f180, {0xfb6f40, 0xc0000ade00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010db0, {0x1171bc0?, 0xc000294540?}, 0xc0005[63](https://github.com/LexisNexis-RBA/ins-sreadmin-cloudflare-lb/actions/runs/4891972239/jobs/8733484850#step:10:64)d10)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1177310?, 0xc000010db0?}}, {0x1171bc0, 0xc000294540}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000448780, 0xc0004487e0, {0xc0004d9920, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00012aaa0, {0x1171bc0?, 0xc00047dcb0?}, 0xc0003dcaf0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xf885c0?, 0xc00012aaa0}, {0x1171bc0, 0xc00047dcb0}, 0xc0003dca80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000202000, {0x1176660, 0xc0000076c0}, 0xc000728b40, 0xc000199e90, 0x1743820, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000202000, {0x1176660, 0xc0000076c0}, 0xc000728b40, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:9[65](https://github.com/LexisNexis-RBA/ins-sreadmin-cloudflare-lb/actions/runs/4891972239/jobs/8733484850#step:10:66) +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v3.33.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2023-05-05T09:51:52Z level=error msg=Terraform invocation failed in /home/runner/work/ins-sreadmin-cloudflare-lb/ins-sreadmin-cloudflare-lb/.terragrunt-download/umK_vABaKPXKCXI1DazAvjCeyXo/T9h2p8m1HnkCZG2au-AxDdYVVvs prefix=[products/testhealth/ct] 
time=2023-05-05T09:51:52Z level=error msg=1 error occurred:
	* exit status 1

### Steps to reproduce

use notification policy resource with v3.35

**Comment by nikuljain** [comment]
can i get an update or help on this

**Comment by nikuljain** [comment]
added debug details as well , please assist
