### ISSUE TITLE
503 Service Unavailable Error When Using Terraform with Cloudflare, resolved by manual UI interaction

### ISSUE THREAD

**Issue by edg4rgarci4** [cloudflare/terraform-provider-cloudflare#2435]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0
+ provider registry.terraform.io/hashicorp/aws v4.66.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected resource(s)

- cloudflare_tunnel
- cloudflare_tunnel_config

My terraform module includes other resources but the issues seems to be specifically with the tunnel config. 

### Terraform configuration files

```hcl
main.tf:
# AWS Route53 Record
resource "aws_route53_record" "this" {
  zone_id = var.route53_zone_id
  name    = var.route53_record_name
  type    = "CNAME"
  ttl     = var.route53_record_ttl
  records = ["${var.tableau_domain}.cdn.cloudflare.net"]
}

# Cloudflare Tunnel
resource "cloudflare_tunnel" "this" {
  account_id = var.account_id
  name       = var.tunnel_name
  secret     = random_id.tunnel_secret.b64_std
  depends_on = [aws_route53_record.this]
}

resource "random_id" "tunnel_secret" {
  byte_length = 35
}

resource "cloudflare_tunnel_config" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_tunnel.this.id

  config {
    origin_request {
      no_tls_verify = var.enable_no_tls_verify
    }
    ingress_rule {
      hostname = var.tableau_domain
      service  = var.ingress_rule_service
    }
    ingress_rule {
      service = "http_status:404"
    }
  }
  depends_on = [aws_route53_record.this]
}

# Cloudflare Record
resource "cloudflare_record" "this" {
  zone_id    = var.zone_id
  name       = var.tableau_domain
  type       = "CNAME"
  value      = "${cloudflare_tunnel.this.id}.cfargotunnel.com"
  proxied    = true
  depends_on = [aws_route53_record.this]
}

# Cloudflare Access Application
resource "cloudflare_access_application" "this" {
  account_id                 = var.account_id
  allowed_idps               = [local.idp_id]
  app_launcher_visible       = true
  auto_redirect_to_identity  = false
  domain                     = var.tableau_domain
  enable_binding_cookie      = false
  http_only_cookie_attribute = true
  logo_url                   = "https://help.tableau.com/current/pro/desktop/en-us/Resources/tableau-logo.png"
  name                       = "Tableau ${local.env_name}"
  session_duration           = "24h"
  type                       = "self_hosted"
  depends_on                 = [aws_route53_record.this]
}

# Cloudflare Access Policies
resource "cloudflare_access_policy" "non_phi_policy" {
  application_id = cloudflare_access_application.this.id
  account_id     = var.account_id
  name           = "Tableau ${local.env_name} Non-PHI Access Policy"
  precedence     = "1"
  decision       = "allow"

  include {
    okta {
      identity_provider_id = local.idp_id
      name                 = ["Tableau Non-PHI Access"]
    }
  }
  depends_on = [aws_route53_record.this]
}

resource "cloudflare_access_policy" "phi_policy" {
  application_id = cloudflare_access_application.this.id
  account_id     = var.account_id
  name           = "Tableau ${local.env_name} PHI Access Policy"
  precedence     = "2"
  decision       = "allow"

  dynamic "include" {
    for_each = var.phi_policy_ips
    content {
      ip = [include.value]
    }
  }
  depends_on = [aws_route53_record.this]
}

# AWS SSM Document & Association
resource "aws_ssm_document" "this" {
  name          = "CloudflaredInstall"
  document_type = "Command"

  content = templatefile("${path.module}/cloudflared_install.json.tpl", {
    tunnel

cloudflared_install.json.tpl:
{
  "schemaVersion": "2.2",
  "description": "Install cloudflared service",
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "downloadCloudflared",
      "inputs": {
        "runCommand": [
          "wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
        ]
      }
    },
    {
      "action": "aws:runShellScript",
      "name": "installCloudflared",
      "inputs": {
        "runCommand": [
          "sudo dpkg -i cloudflared-linux-amd64.deb"
        ]
      }
    },
    {
      "action": "aws:runShellScript",
      "name": "cloudflaredInstall",
      "inputs": {
        "runCommand": [
          "sudo cloudflared service install ${tunnel_token}"
        ]
      }
    }
  ]
}
```

### Link to debug output

https://gist.github.com/edg4rgarci4/b545a181d0089ce928c9bc4d582288c8

### Expected output

I would expect a working connection to the configured hostname. Instead I get:
"This page isn’t working ________ is currently unable to handle this request.
HTTP ERROR 503"

Even though the tunnel connection in the UI shows as healthy and I am able to CURL the service on the server and confirm the origin server is correctly serving the content. 

### Actual output

"This page isn’t working ________ is currently unable to handle this request.
HTTP ERROR 503"

### Steps to reproduce

1. Define Terraform configuration to create a tunnel 
2. Apply Terraform configuration
3. Try to accessed configured hostname
4. Get a 503 error
5. Navigate to Public Hostname section of the configured tunnel > Edit (no changes) and save. 503 error is gone.

**Comment by edg4rgarci4** [comment]
sorry I was a bit lazy to simplify my example config and missed the part about dynamic expressions... just noticed https://github.com/cloudflare/terraform-provider-cloudflare/issues/2233 so it's ok if this gets closed as duplicate. I guess the questions I have now would be more for https://community.cloudflare.com/ or support.  fwiw here's reproduction case

```hcl
resource "cloudflare_tunnel" "this" {
  account_id = "REDACTED_ACCOUNT_ID"
  name       = "example-tunnel"
  secret     = random_id.tunnel_secret.b64_std
}

resource "random_id" "tunnel_secret" {
  byte_length = 35
}

resource "cloudflare_tunnel_config" "this" {
  account_id = "REDACTED_ACCOUNT_ID"
  tunnel_id  = cloudflare_tunnel.this.id

  config {
    origin_request {
      no_tls_verify = true
    }
    ingress_rule {
      hostname = "example.biz"
      service  = "http://localhost:80"
    }
    ingress_rule {
      service = "http_status:404"
    }
  }
}

# Cloudflare Record
resource "cloudflare_record" "this" {
  zone_id    = "REDACTED_ZONE_ID"
  name       = "example"
  type       = "CNAME"
  value      = "${cloudflare_tunnel.this.id}.cfargotunnel.com"
  proxied    = true
}
```

**Comment by jacobbednarz** [comment]
cool as - thanks for the confirmation. #2072 is already on the team's radar to address so let's close this and track in the one place.

**Comment by edg4rgarci4** [comment]
🤔 I still have this issue with the 4.8.0 provider as in my origin_request configurations aren't being set. Except this time I can't do a TF plan after the manual changes for the Public Hostname configuration in the GUI

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-cloudflare_v4.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10110e1c8]

goroutine 102 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.parseOriginRequest({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14000035f88, ...})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_tunnel_config.go:122 +0x38
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTunnelConfigRead({0x101778128, 0x1400043a480}, 0x1400009e600, {0x1017674e0?, 0x14000716900})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_tunnel_config.go:233 +0xa54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x140003d61c0, {0x101778160, 0x1400042a7e0}, 0xd?, {0x1017674e0, 0x14000716900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140003d61c0, {0x101778160, 0x1400042a7e0}, 0x140003db040, {0x1017674e0, 0x14000716900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400012b308, {0x101778160?, 0x1400042a5a0?}, 0x140004d5500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x10177dd90?, 0x1400012b308?}}, {0x101778160?, 0x1400042a5a0?}, 0x140004d5380?)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:105 +0x264
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0x140003d0b40, 0x140003d0ba0, {0x1400007ca20, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400053d220, {0x101778160?, 0x1400041a870?}, 0x140004d0f00)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x101738080?, 0x1400053d220}, {0x101778160, 0x1400041a870}, 0x140001991f0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000cc5a0, {0x10177ce18, 0x14000003d40}, 0x140000d87e0, 0x1400041b200, 0x101d624b0, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140000cc5a0, {0x10177ce18, 0x14000003d40}, 0x140000d87e0, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28c

Error: The terraform-provider-cloudflare_v4.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by edg4rgarci4** [comment]
@jacobbednarz given the above please let me know if this can be re-opened or if I should open a new issue.
