### ISSUE TITLE
Panic and crash on creation of multiple pages projects

### ISSUE THREAD

**Issue by dvasdekis** [cloudflare/terraform-provider-cloudflare#2597]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.1
on windows_amd64

provider registry.terraform.io/auth0/auth0 v0.45.0
provider registry.terraform.io/cloudflare/cloudflare v4.9.0
provider registry.terraform.io/cyrilgdn/postgresql v1.19.0
provider registry.terraform.io/hashicorp/aws v4.61.0
provider registry.terraform.io/hashicorp/random v3.4.3

### Affected resource(s)

cloudflare_pages_project
cloudflare_pages_domain

### Terraform configuration files

```hcl
# Set local variables for cloudflare
locals {
  cloudflare_connect_project_name   = "site1"
  cloudflare_connect_project_domain = "site1.com"
  cloudflare_place_project_name     = "site2"
  cloudflare_place_project_domain   = "site2.com"
}

# Get the zone id for the connect domain
data "cloudflare_zone" "connect-zone" {
  name       = local.cloudflare_connect_project_domain
  account_id = var.CLOUDFLARE_ACCOUNT_ID
}

resource "cloudflare_record" "connect-record" {
  zone_id = data.cloudflare_zone.connect-zone.id
  name    = terraform.workspace == "prd" ? "www" : terraform.workspace
  proxied = true
  type    = "CNAME"
  value   = "${local.cloudflare_connect_project_name}-${terraform.workspace}.pages.dev"
  ttl     = 1
}

# Redirect root to the same domain as www (the production domain)
resource "cloudflare_record" "connect-record-root" {
  count   = terraform.workspace == "prd" ? 1 : 0
  zone_id = data.cloudflare_zone.connect-zone.id
  proxied = true
  name    = "@"
  type    = "CNAME"
  value   = "${local.cloudflare_connect_project_name}-${terraform.workspace}.pages.dev"
  ttl     = 1
}

# If prd, deploy it to www.domain, otherwise deploy it to a subdomain
resource "cloudflare_pages_domain" "connect-domain" {
  account_id   = var.CLOUDFLARE_ACCOUNT_ID
  project_name = "${local.cloudflare_connect_project_name}-${terraform.workspace}"
  domain       = terraform.workspace == "prd" ? "www.${local.cloudflare_connect_project_domain}" : "${terraform.workspace}.${local.cloudflare_connect_project_domain}"
}

# We deploy to the below with the cloudflare pages github action
resource "cloudflare_pages_project" "connect-frontend" {
  account_id        = var.CLOUDFLARE_ACCOUNT_ID
  name              = "${local.cloudflare_connect_project_name}-${terraform.workspace}"
  production_branch = "main"
  build_config {
    build_command   = "yarn build"
    root_dir        = "frontend"
    destination_dir = "build"
    # web_analytics_tag   = ""
    # web_analytics_token = ""
  }
  # Define environment variables for the preview and production environments
  deployment_configs {
    preview {
      environment_variables = {
        # Set the version of software to use for the preview environment
        # AWS was using buildimage Ubuntu standard:6.0 for frontend (5.0 for backend)
        # See https://ap-southeast-2.console.aws.amazon.com/codesuite/codebuild/772508458330/projects/proptechdev-fe-production/details?region=ap-southeast-2
        # and https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
        NODE_VERSION = "16.16"
      }
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["preview_flag"]
    }
    production {
      environment_variables = {
        # Set the version of software to use for the production environment
        NODE_VERSION = "16.16"
      }
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["production_flag"]
    }
  }
}

# Get the zone id for the connect domain
data "cloudflare_zone" "place-zone" {
  name       = local.cloudflare_place_project_domain
  account_id = var.CLOUDFLARE_ACCOUNT_ID
}

# If prd, deploy it to www.domain, otherwise deploy it to a subdomain
resource "cloudflare_pages_domain" "place-domain" {
  account_id   = var.CLOUDFLARE_ACCOUNT_ID
  project_name = "${local.cloudflare_place_project_name}-${terraform.workspace}"
  domain       = terraform.workspace == "prd" ? "www.${local.cloudflare_place_project_domain}" : "${terraform.workspace}.${local.cloudflare_place_project_domain}"
}

resource "cloudflare_record" "place-record" {
  zone_id = data.cloudflare_zone.place-zone.id
  name    = terraform.workspace == "prd" ? "www" : terraform.workspace
  proxied = true
  type    = "CNAME"
  value   = "${local.cloudflare_place_project_name}-${terraform.workspace}.pages.dev"
  ttl     = 1
}

# Redirect root to the same domain as www (the production domain)
resource "cloudflare_record" "place-record-root" {
  count   = terraform.workspace == "prd" ? 1 : 0
  zone_id = data.cloudflare_zone.place-zone.id
  proxied = true
  name    = "@"
  type    = "CNAME"
  value   = "${local.cloudflare_place_project_name}-${terraform.workspace}.pages.dev"
  ttl     = 1
}

# We deploy to the below with the cloudflare pages github action
resource "cloudflare_pages_project" "place-frontend" {
  account_id        = var.CLOUDFLARE_ACCOUNT_ID
  name              = "${local.cloudflare_place_project_name}-${terraform.workspace}"
  production_branch = "main"
  build_config {
    build_command   = "yarn build"
    root_dir        = "frontend_place"
    destination_dir = "build"
    # web_analytics_tag   = ""
    # web_analytics_token = ""
  }
  # Define environment variables for the preview and production environments
  deployment_configs {
    preview {
      environment_variables = {
        # Set the version of software to use for the preview environment
        # AWS was using buildimage Ubuntu standard:6.0 for frontend (5.0 for backend)
        # See https://ap-southeast-2.console.aws.amazon.com/codesuite/codebuild/772508458330/projects/proptechdev-fe-production/details?region=ap-southeast-2
        # and https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
        NODE_VERSION = "16.16"
      }
      placement {}
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["preview_flag"]
    }
    production {
      environment_variables = {
        # Set the version of software to use for the production environment
        NODE_VERSION = "16.16"
      }
      placement {}
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["production_flag"]
    }
  }
}
```

### Link to debug output

https://gist.github.com/dvasdekis/1150a8533c60eae83bc6ce268981809f

### Panic output

Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v4.9.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 148 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildDeploymentConfig({0xed42e0?, 0xc0006df3b0})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_pages_project.go:129 +0x1188
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildPagesProject(_)
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_pages_project.go:286 +0x64e
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflarePagesProjectCreate({0x11d91a8, 0xc0006de9c0}, 0x0?, {0x1013780?, 0xc000462210?})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_pages_project.go:359 +0xd9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000391ce0, {0x11d91e0, 0xc0005717d0}, 0xd?, {0x1013780, 0xc000462210})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000391ce0, {0x11d91e0, 0xc0005717d0}, 0xc000947110, 0xc000574800, {0x1013780, 0xc000462210})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000112d8, {0x11d91e0?, 0xc0005715f0?}, 0xc000482190)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x11df010?, 0xc0000112d8?}}, {0x11d91e0, 0xc0005715f0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc0003c0b40, 0xc0003c0ba0, {0xc000454820, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0004e8820, {0x11d91e0?, 0xc000570000?}, 0xc0001ae070)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xfdf2c0?, 0xc0004e8820}, {0x11d91e0, 0xc000570000}, 0xc0001ae000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004da5a0, {0x11ddf98, 0xc0006024e0}, 0xc000976000, 0xc000403c20, 0x17e95a0, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0004da5a0, {0x11ddf98, 0xc0006024e0}, 0xc000976000, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.0/server.go:957 +0x18c

Error: The terraform-provider-cloudflare_v4.9.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)

### Expected output

Cloudflare would create the 2 pages projects specified in the Terraform

### Actual output

Panic

### Steps to reproduce

1. `terraform init`
2. `terraform apply`

### Additional factoids

Happy to share my private account details if needed for debugging - just tell me where I can send them

**Comment by dvasdekis** [comment]
I've identified a smaller config that still crashes, will reopen with that.
