### ISSUE TITLE
Re-ordering of a `cloudflare_ruleset` `rules` block above a block containing `logging` block causes crash

### ISSUE THREAD

**Issue by jsifuentes** [cloudflare/terraform-provider-cloudflare#2609]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.2
on linux_arm64
+ provider registry.terraform.io/carlpett/sops v0.7.2
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0
+ provider registry.terraform.io/datadog/datadog v3.22.0
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected resource(s)

`cloudflare_ruleset` when a rule is created without `logging` above a rule with `logging { enabled = true }`

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "firewall_custom" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_firewall_custom"
  zone_id = ""

  rules {
    description = "..."

    action = "skip"
    action_parameters {
      phases   = ["http_ratelimit"]
      products = ["rateLimit"]
      ruleset  = "current"
    }
    enabled    = true
    expression = "(cf.bot_management.verified_bot)"
    logging {
      enabled = true
    }
  }

  rules {
    description = "..."

    action = "skip"
    action_parameters {
      phases   = ["http_ratelimit"]
      products = ["rateLimit"]
      ruleset  = "current"
    }
    enabled    = true
    expression = "(ip.src in { ... })"
    logging {
      enabled = true
    }
  }
}



====== update to ======



resource "cloudflare_ruleset" "firewall_custom" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_firewall_custom"
  zone_id = ""

  rules {
    description = "..."
    
    action = "skip"
    action_parameters {
      phases   = ["http_ratelimit"]
      products = ["bic", "hot", "securityLevel", "uaBlock", "waf", "zoneLockdown", "rateLimit"]
      ruleset  = "current"
    }
    enabled = true
    expression = "(http.host matches \"^abagsgssd$\")"
  }

  rules {
    description = "..."

    action = "block"
    enabled = true
    expression = "(http.host matches \"^hjkdnfhkjdnh\")"
  }

  rules {
    description = "..."

    action = "skip"
    action_parameters {
      phases   = ["http_ratelimit"]
      products = ["rateLimit"]
      ruleset  = "current"
    }
    enabled    = true
    expression = "(cf.bot_management.verified_bot)"
    logging {
      enabled = true
    }
  }

  rules {
    description = "..."

    action = "skip"
    action_parameters {
      phases   = ["http_ratelimit"]
      products = ["rateLimit"]
      ruleset  = "current"
    }
    enabled    = true
    expression = "(ip.src in { ... })"
    logging {
      enabled = true
    }
  }
}
```

### Link to debug output

https://gist.github.com/jsifuentes/ba8a99b9b1f7a99ffff2a2d563ca242b

### Expected output

╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_ruleset.firewall_custom, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].logging: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Actual output

╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_ruleset.firewall_custom, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].logging: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Steps to reproduce

- Be in a state already where your first firewall rule has logging enabled and is created on Cloudflare.
- Create a new firewall rule above the first firewall rule with logging disabled

### Additional factoids

* To fix this issue, I had to add a `logging { enabled = false }` block to the new rules I created. Found out after submitting this report. I also observed that the rules had been created on Cloudflare and also had logging enabled even though the Terraform code did not define a `logging` block.

**Comment by jsoh** [comment]
We are experiencing a similar problem with reordering custom rules, except from the Cloudflare web UI dashboard.

Terraform v1.5.2
on linux_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.8.0

We have a `cloudflare_ruleset.zone_custom_waf` resource. There are no issues running `plan` and `apply`. Example snippet as follows:

```terraform
resource "cloudflare_ruleset" "zone_custom_waf" {
  zone_id = local.cloudflare_zone_id
  name    = "default"
  kind    = "zone"
  phase   = "http_request_firewall_custom"

  rules {...}
  rules {...}
  rules {...}
}
```

However, if anyone reorders any custom rule from the web UI dashboard, we receive the following errors when a `terraform plan` is executed:

```
cloudflare_ruleset.zone_custom_waf: Refreshing state... [id=xxxxxxxxxx]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-cloudflare_v4.8.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 608 [running]:
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualitySetElements({0xca7d60, 0x400090ad80}, {{{0x40009c0380, 0x5, 0x8}}, {0xcaac28, 0x4000ac9f20}, {0xcaac28, 0x4000712f00}}, 0x400090ad20)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_set.go:145 +0xa70
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualitySet({0xca7d60, 0x400090ad80}, {{{0x40009c0380, 0x5, 0x8}}, {0xcaac28, 0x4000ac9f20}, {0xcaac28, 0x4000712f00}}, 0x400090ad20)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_set.go:27 +0x30c
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEquality({0xca7d60, 0x400090a090}, {{{0x40009c0380, 0x5, 0x8}}, {0xcaac28, 0x4000ac9f20}, {0xcaac28, 0x4000712f00}}, 0x400090ad20)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality.go:79 +0x370
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityObjectAttributes({0xca7d60, 0x400090a090}, {{{0x400007a360, 0x4, 0x6}}, {0xcaab98, 0x40003933e0}, {0xcaab98, 0x40004ad158}}, 0x400090a030)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_object.go:154 +0x6a0
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityObject({0xca7d60, 0x400090a090}, {{{0x400007a360, 0x4, 0x6}}, {0xcaab98, 0x40003933e0}, {0xcaab98, 0x40004ad158}}, 0x400090a030)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_object.go:27 +0x30c
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEquality({0xca7d60, 0x40008e1fb0}, {{{0x400007a360, 0x4, 0x6}}, {0xcaab98, 0x40003933e0}, {0xcaab98, 0x40004ad158}}, 0x400090a030)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality.go:77 +0x328
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityListElements({0xca7d60, 0x40008e1fb0}, {{{0x4000975100, 0x3, 0x4}}, {0xcaa9e8, 0x4000bcc840}, {0xcaa9e8, 0x40007192c0}}, 0x40008e1f50)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_list.go:152 +0x634
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityList({0xca7d60, 0x40008e1fb0}, {{{0x4000975100, 0x3, 0x4}}, {0xcaa9e8, 0x4000bcc840}, {0xcaa9e8, 0x40007192c0}}, 0x40008e1f50)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_list.go:27 +0x30c
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEquality({0xca7d60, 0x40008e1ef0}, {{{0x4000975100, 0x3, 0x4}}, {0xcaa9e8, 0x4000bcc840}, {0xcaa9e8, 0x40007192c0}}, 0x40008e1f50)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality.go:71 +0x250
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityObjectAttributes({0xca7d60, 0x40008e1ef0}, {{{0x40005e3620, 0x2, 0x2}}, {0xcaab98, 0x4000393428}, {0xcaab98, 0x40004ad290}}, 0x40008e1e90)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_object.go:154 +0x6a0
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityObject({0xca7d60, 0x40008e1ef0}, {{{0x40005e3620, 0x2, 0x2}}, {0xcaab98, 0x4000393428}, {0xcaab98, 0x40004ad290}}, 0x40008e1e90)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_object.go:27 +0x30c
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEquality({0xca7d60, 0x40008841e0}, {{{0x40005e3620, 0x2, 0x2}}, {0xcaab98, 0x4000393428}, {0xcaab98, 0x40004ad290}}, 0x40008e1e90)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality.go:77 +0x328
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityListElements({0xca7d60, 0x40008841e0}, {{{0x40008196f0, 0x1, 0x1}}, {0xcaa9e8, 0x4000a41080}, {0xcaa9e8, 0x4000884180}}, 0x4000a7eee0)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_list.go:152 +0x634
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualityList({0xca7d60, 0x40008841e0}, {{{0x40008196f0, 0x1, 0x1}}, {0xcaa9e8, 0x4000a41080}, {0xcaa9e8, 0x4000884180}}, 0x4000a7eee0)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_list.go:27 +0x30c
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEquality({0xca7d60, 0x4000786750}, {{{0x40008196f0, 0x1, 0x1}}, {0xcaa9e8, 0x4000a41080}, {0xcaa9e8, 0x4000884180}}, 0x4000a7eee0)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality.go:71 +0x250
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.SchemaSemanticEquality({0xca7d60, 0x4000786750}, {{{0xae9524, 0x5}, {0xcadce8, 0x400037ce60}, {{0xcac6e0, 0x4000d9e900}, {0x9a6640, 0x4000d56030}}}, ...}, ...)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwserver/schema_semantic_equality.go:126 +0x4d4
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x4000402000, {0xca7d60, 0x4000786750}, 0x4000786840, 0x4000a7f400)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwserver/server_readresource.go:135 +0x7cc
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x4000402000, {0xca7d60?, 0x4000786600?}, 0x4000770780)
	github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0x4000356b10, 0x4000356b70, {0x4000078a00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x4000512820, {0xca7d60?, 0x4000769b00?}, 0x40000af980)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xab4a80?, 0x4000512820}, {0xca7d60, 0x4000769b00}, 0x4000503650, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x40005045a0, {0xcaca18, 0x4000003a00}, 0x40006b7d40, 0x4000381ec0, 0x12a2350, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xc28
google.golang.org/grpc.(*Server).handleStream(0x40005045a0, {0xcaca18, 0x4000003a00}, 0x40006b7d40, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0x80c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x278

Error: The terraform-provider-cloudflare_v4.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

If we restore the order back to how it was originally (from the web UI to match our terraform state), the `plan` runs clean and  there is no panic crash.

**Comment by jsoh** [comment]
Additional note regarding my earlier comment: The panic crash only happens when we reorder a rule where the action is `skip`. If we reorder any other action types (i.e. `managed_challenge`, `block`, or `log`), there is no crash.
