### ISSUE TITLE
cloudflare_teams_rule  panic: interface conversion: interface {} is nil...

### ISSUE THREAD

**Issue by nikasmonk** [cloudflare/terraform-provider-cloudflare#2680]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

4.12.0

### Affected resource(s)

cloudflare_teams_rule

### Terraform configuration files

```hcl
resource "cloudflare_teams_rule" "test5" {
  account_id  = <--MASKED-->
  name        = "egress policy 5"
  description = "egr 5"
  precedence  = 1
  # enabled     = true
  action  = "egress"
  filters = ["egress"]
  traffic = "net.dst.ip == 5.5.5.5"
  rule_settings {
  }
}
```

### Link to debug output

https://gist.github.com/nikasmonk/ea819c49dd0a36d34b8a96869d0d1096

### Panic output

2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: panic: interface conversion: interface {} is nil, not map[string]interface {}
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0:
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: goroutine 145 [running]:
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.inflateTeamsRuleSettings({0x103553780?, 0x14000717518?})
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:259 +0xd74
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTeamsRuleCreate({0x1037046c8, 0x140008206c0}, 0x0?, {0x1036f4060?, 0x140008068f0?})
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:88 +0xa0
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140003b80e0, {0x103704700, 0x140003b1500}, 0xd?, {0x1036f4060, 0x140008068f0})
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0xe8
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140003b80e0, {0x103704700, 0x140003b1500}, 0x14000300270, 0x14000990980, {0x1036f4060, 0x140008068f0})
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0x8a0
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000d368, {0x103704700?, 0x140003b1320?}, 0x140005340f0)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xb78
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x10370a448?, 0x1400000d368?}}, {0x103704700, 0x140003b1320}, 0x0?)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:37 +0x58
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0x140003b0f00, 0x1400081bce0, 0x140003b0f30, 0x140003b0f60, {0x1400037a8a0, 0x2, 0x2}}, {0x103704700?, 0x140003b02d0?}, 0x140005340a0)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x100
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000225a40, {0x103704700?, 0x140002621e0?}, 0x140000f0770)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x3bc
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1036be5e0?, 0x14000225a40}, {0x103704700, 0x140002621e0}, 0x140000f0700, 0x0)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: google.golang.org/grpc.(*Server).processUnaryRPC(0x140002561e0, {0x103709458, 0x14000782340}, 0x14000a2e000, 0x1400045ad50, 0x103cfb5e0, 0x0)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	google.golang.org/grpc@v1.56.1/server.go:1337 +0xc90
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: google.golang.org/grpc.(*Server).handleStream(0x140002561e0, {0x103709458, 0x14000782340}, 0x14000a2e000, 0x0)
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	google.golang.org/grpc@v1.56.1/server.go:959 +0x84
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-08-11T12:27:45.965+0300 [DEBUG] provider.terraform-provider-cloudflare_v4.12.0: 	google.golang.org/grpc@v1.56.1/server.go:957 +0x16c
2023-08-11T12:27:45.966+0300 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/4.12.0/darwin_arm64/terraform-provider-cloudflare_v4.12.0 pid=37053 error="exit status 2"
2023-08-11T12:27:45.966+0300 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Canceled desc = context canceled"
2023-08-11T12:27:45.966+0300 [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Canceled desc = context canceled"
2023-08-11T12:27:45.966+0300 [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-08-11T12:27:45.966+0300 [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-08-11T12:27:45.971+0300 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-08-11T12:27:45.971+0300 [ERROR] vertex "cloudflare_teams_rule.test5" error: Plugin did not respond
2023-08-11T12:27:45.974+0300 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-08-11T12:27:45.974+0300 [ERROR] vertex "cloudflare_teams_rule.test4 (destroy)" error: Plugin did not respond
2023-08-11T12:27:45.978+0300 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-08-11T12:27:45.978+0300 [ERROR] vertex "cloudflare_access_policy.cf_policy (destroy)" error: Request cancelled
╷

### Expected output

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual output

Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
Stack trace from the terraform-provider-cloudflare_v4.12.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 39 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.inflateTeamsRuleSettings({0x1039e3780?, 0x14000812000?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:259 +0xd74
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTeamsRuleCreate({0x103b946c8, 0x1400050d770}, 0x0?, {0x103b84060?, 0x140005402c0?})
	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:88 +0xa0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140004520e0, {0x103b94700, 0x1400061aed0}, 0xd?, {0x103b84060, 0x140005402c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140004520e0, {0x103b94700, 0x1400061aed0}, 0x14000459d40, 0x140000ba280, {0x103b84060, 0x140005402c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400019f350, {0x103b94700?, 0x1400061acf0?}, 0x140002be820)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x103b9a448?, 0x1400019f350?}}, {0x103b94700, 0x1400061acf0}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0x1400044af00, 0x1400051b280, 0x1400044af30, 0x1400044af60, {0x14000414880, 0x2, 0x2}}, {0x103b94700?, 0x1400061a9c0?}, 0x140002be780)
	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x100
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140002bba40, {0x103b94700?, 0x1400061a1b0?}, 0x140001e00e0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x103b4e5e0?, 0x140002bba40}, {0x103b94700, 0x1400061a1b0}, 0x140001e0070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002f81e0, {0x103b99458, 0x1400008a820}, 0x14000564000, 0x140004f6d50, 0x10418b5e0, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140002f81e0, {0x103b99458, 0x1400008a820}, 0x14000564000, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.1/server.go:957 +0x16c

Error: The terraform-provider-cloudflare_v4.12.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-08-11T12:29:46.831+0300 [DEBUG] provider: plugin exited

### Steps to reproduce

1. Make sure you have the provider.tf file with actual api_token like:
```
provider "cloudflare" {

  api_token = "TOKEN"

}
```
3.` terraform init`
4.
```
cat > "main.tf" << EOF
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4"
    }
  }
}
resource "cloudflare_teams_rule" "test5" {
  account_id  = "<--YOUR_ACCOUNT_ID-->"
  name        = "egress policy 5"
  description = "egr 5"
  precedence  = 1
  # enabled     = true
  action  = "egress"
  filters = ["egress"]
  traffic = "net.dst.ip == 5.5.5.5"
  rule_settings {
  }
}
EOF
```
5. terraform apply --auto-approve

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_rule

**Comment by jacobbednarz** [comment]
why are you using an empty `rule_setting` block?

**Comment by nikasmonk** [comment]
@jacobbednarz i'v try to use
```
    block_page_enabled = false
    block_page_reason  = ""
```
in rule_settings, still not work.

**Comment by jacobbednarz** [comment]
an empty `rule_settings` is expected to cause unknown behaviour as you're sending an empty/nil object. if you no longer wish to use it, you need to remove the entire thing.

**Comment by nikasmonk** [comment]
@jacobbednarz thank you! Solved by:
`terraform state list`
`terraform state rm ...`
And using valid `rule_settings`
