### ISSUE TITLE
cloudflare_list_item broken - panic

### ISSUE THREAD

**Issue by 0x4c6565** [cloudflare/terraform-provider-cloudflare#3000]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.5
Provider v4.20.0

### Affected resource(s)

cloudflare_list_item

### Terraform configuration files

```hcl
resource "cloudflare_list_item" "redirect1" {
  account_id = var.cloudflare_account_id
  list_id    = cloudflare_list.redirects.id
  redirect {
    source_url            = "https://some.url"
    include_subdomains    = "disabled"
    target_url            = "https://someother.url"
    status_code           = 301
    preserve_query_string = "enabled"
    subpath_matching      = "disabled"
    preserve_path_suffix  = "disabled"
  }
}

resource "cloudflare_list_item" "redirect2" {
  account_id = var.cloudflare_account_id
  list_id    = cloudflare_list.redirects.id
  redirect {
    source_url            = "https://some.url"
    include_subdomains    = "disabled"
    target_url            = "https://someother.url"
    status_code           = 301
    preserve_query_string = "enabled"
    subpath_matching      = "disabled"
    preserve_path_suffix  = "disabled"
  }
}
```

### Link to debug output

[Debug Output](https://gist.github.com/0x4c6565/f311ca581d0582d31413d95a99d6662f)

### Panic output

```
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: panic: interface conversion: interface {} is []interface {}, not string
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: goroutine 129 [running]:
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.getSearchTerm(0xc0008aa120?)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_list_item.go:208 +0x1cd
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareListItemCreate({0x1397268, 0xc0008d3230}, 0x0?, {0x1199e40?, 0xc000436fd0})
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_list_item.go:61 +0x669
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000310a80, {0x13972a0, 0xc0005fd080}, 0xd?, {0x1199e40, 0xc000436fd0})
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:778 +0x12e
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000310a80, {0x13972a0, 0xc0005fd080}, 0xc00041b6c0, 0xc000998880, {0x1199e40, 0xc000436fd0})
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:909 +0xa7e
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010030, {0x13972a0?, 0xc0005fcea0?}, 0xc0005fe3c0)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xe8d
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x139daa0?, 0xc000010030?}}, {0x13972a0, 0xc0005fcea0}, 0x0?)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x5a
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x13971f8?, {0x13972a0?, 0xc0005fcb70?}, 0xc0005fe370)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0003a5360, {0x13972a0?, 0xc0005fc180?}, 0xc0003ae000)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x574
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x11660e0?, 0xc0003a5360}, {0x13972a0, 0xc0005fc180}, 0xc000998000, 0x0)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006e6000, {0x13972a0, 0xc0005fc0f0}, {0x139c258, 0xc0003a24e0}, 0xc000884000, 0xc0006e48d0, 0x1a4d798, 0x0)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	google.golang.org/grpc@v1.59.0/server.go:1343 +0xe49
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: google.golang.org/grpc.(*Server).handleStream(0xc0006e6000, {0x139c258, 0xc0003a24e0}, 0xc000884000)
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	google.golang.org/grpc@v1.59.0/server.go:1737 +0xca6
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	google.golang.org/grpc@v1.59.0/server.go:986 +0x8c
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-12-11T09:32:59.302Z [DEBUG] provider.terraform-provider-cloudflare_v4.20.0: 	google.golang.org/grpc@v1.59.0/server.go:997 +0x15c
2023-12-11T09:32:59.304Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
```

### Expected output

No panic

### Actual output

```
2023-12-11T09:32:59.662Z [TRACE] Re-validating config for "cloudflare_list_item.preact_redirects[\"redacted\"]"
2023-12-11T09:32:59.662Z [TRACE] GRPCProvider.v6: ValidateResourceConfig
2023-12-11T09:32:59.662Z [TRACE] Re-validating config for "cloudflare_list_item.preact_redirects[\"redacted\"]"
2023-12-11T09:32:59.662Z [TRACE] GRPCProvider.v6: ValidateResourceConfig
2023-12-11T09:32:59.662Z [ERROR] plugin6.(*GRPCProvider).ValidateResourceConfig: error="rpc error: code = Canceled desc = context canceled"
2023-12-11T09:32:59.662Z [ERROR] vertex "cloudflare_list_item.preact_redirects[\"redacted
```

### Steps to reproduce

Attempt to create multiple cloudflare_list_item resources

### Additional factoids

It would appear that between 4.17.0 and 4.20.0 a breaking change has been implemented which causes cloudflare_list_item resources to panic. We're attempting to create ~400 redirects.

In v4.17.0 the plan takes a long time to complete, whereas in 4.20.0 the plan completes almost immediately.

**Comment by 0x4c6565** [comment]
Added debug output

**Comment by Cyb3r-Jak3** [comment]
Seems similar to 2970. My guess is https://github.com/cloudflare/terraform-provider-cloudflare/pull/2975 should fix this
