### ISSUE TITLE
cloudflare provider thoroughly breaks `cdktf convert`

### ISSUE THREAD

**Issue by infowolfe** [cloudflare/terraform-provider-cloudflare#3331]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.8.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.33.0
+ provider registry.terraform.io/hashicorp/aws v5.49.0
cdktf: 0.20.7

### Affected resource(s)

all

### Terraform configuration files

```hcl
# Add a record to the domain
resource "cloudflare_record" "example" {
  zone_id = var.cloudflare_zone_id
  name    = "terraform"
  value   = "192.0.2.1"
  type    = "A"
  ttl     = 3600
}

# Add a record requiring a data map
resource "cloudflare_record" "_sip_tls" {
  zone_id = var.cloudflare_zone_id
  name    = "_sip._tls"
  type    = "SRV"

  data {
    service  = "_sip"
    proto    = "_tls"
    name     = "terraform-srv"
    priority = 0
    weight   = 0
    port     = 443
    target   = "example.com"
  }
}
```

### Link to debug output

https://gist.github.com/infowolfe/599ecee5575b24ef3bdf01c32e78dd7c

### Panic output

Adding package @cdktf/provider-cloudflare @ 11.11.0
Internal Error: unexpected array
Error: unexpected array
    at Parser.renderAttributeType (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:205:23)
    at Parser.renderAttributesForBlock (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:264:31)
    at Parser.resourceFrom (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:124:31)
    at ResourceParser.parse (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:466:33)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:121
    at Array.map (<anonymous>)
    at TerraformProviderGenerator.buildResourceModels (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:75)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:93:31
    at Array.reduce (<anonymous>)
    at convertToTypescript (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:91:79)
Collecting Debug Information...
/usr/local/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: unexpected array
    at Parser.renderAttributeType (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:205:23)
    at Parser.renderAttributesForBlock (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:264:31)
    at Parser.resourceFrom (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:124:31)
    at ResourceParser.parse (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:466:33)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:121
    at Array.map (<anonymous>)
    at TerraformProviderGenerator.buildResourceModels (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:75)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:93:31
    at Array.reduce (<anonymous>)
    at convertToTypescript (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:91:79) {
  language: 'python',
  __type: 'Internal'
}

Node.js v20.13.1

### Expected output

cdktf should have given me the python code matching the example configfile for a cloudflare_record.

### Actual output

see Panic output.

### Steps to reproduce

- install cdktf
- create a project
- add the cloudflare/cloudflare provider
- try to convert some hcl to your favorite programming language

### Additional factoids

Some of cloudflare's decisions with this provider are incredibly frustrating #2407.
The fact that I can't `allow_overwrite=True` without doing `Fn.trimsuffix()` is beyond belief (and causes a bunch of downstream headaches trying to work around it).

**Comment by jacobbednarz** [comment]
thanks for the report! 

we don't do anything specific for cdktf nor do we maintain anything related to it so i'd suggest chatting with the maintainers at https://github.com/cdktf/cdktf-provider-cloudflare or the cdktf core folks depending on what the specific bug you are hitting.

if you have specific improvements that come from those discussions, i'm happy to review PRs to get that working.

**Comment by infowolfe** [comment]
Ah, I wasn't explicitly using the prebuilt provider, so I'll ping them and raise this.
