### ISSUE TITLE
Exceeding zonelockdown limit of entries gives unhelpful error

### ISSUE THREAD

**Issue by upstart-swiss** [cloudflare/terraform-provider-cloudflare#964]
### Terraform version
v0.13.4

### Affected resource(s)
cloudflare_zone_lockdown

### Terraform configuration files
<not sharing> Zonelockdown w/ over 250 configurations

### Debug output
<can provide if needed>

### Expected behavior
API should throw a better error than `Error: rpc error: code = Unavailable desc = transport is closing`

### Actual behavior
Error: rpc error: code = Unavailable desc = transport is closing

### Steps to reproduce
Create a zonelockdown over 250 configurations and try to apply

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
Can you please post the full output of `TF_LOG=DEBUG` with this report? The line you are referencing isn't the error; it's when the apply unsuccessfully completes.

**Comment by upstart-swiss** [comment]
Here's the relevant section I believe:
```
[2021-02-19T21:17:34.997Z] panic: interface conversion: interface {} is nil, not string

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: goroutine 28 [running]:

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareZoneLockdownUpdate(0xc0000b4070, 0x10de300, 0xc000610180, 0x24, 0x1892c40)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_zone_lockdown.go:196 +0x86f

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0006de3f0, 0xc0000a01e0, 0xc0007dae40, 0x10de300, 0xc000610180, 0xf89b01, 0xc00082f298, 0xc000b4b6b0)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:316 +0x273

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0006f2000, 0xc0002bfa10, 0xc0000a01e0, 0xc0007dae40, 0xc000454038, 0xc00068e001, 0xf8b840)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x99

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0006e0040, 0x127b400, 0xc0005ca270, 0xc0000b41c0, 0xc0006e0040, 0xc0005ca270, 0xc000556b78)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10a4fc0, 0xc0006e0040, 0x127b400, 0xc0005ca270, 0xc0005520c0, 0x0, 0x127b400, 0xc0005ca270, 0xc0002b8000, 0x6ad4)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000602c00, 0x1284a80, 0xc0006c2900, 0xc0001ae000, 0xc000502900, 0x1851540, 0x0, 0x0, 0x0)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: google.golang.org/grpc.(*Server).handleStream(0xc000602c00, 0x1284a80, 0xc0006c2900, 0xc0001ae000, 0x0)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00050c1d0, 0xc000602c00, 0x1284a80, 0xc0006c2900, 0xc0001ae000)

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa5

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: created by google.golang.org/grpc.(*Server).serveStreams.func1

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.618Z [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.620Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/cloudflare/cloudflare/2.11.0/linux_amd64/terraform-provider-cloudflare_v2.11.0 pid=537 error="exit status 2"

[2021-02-19T21:17:34.997Z] 2021-02-19T21:17:34.620Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

[2021-02-19T21:17:34.998Z] 2021/02/19 21:17:34 [DEBUG] module.firewall_rules.cloudflare_zone_lockdown.PBU_Staging: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing

```

This hits whenever a zonelockdown's configuration count exceeds 250.

**Comment by upstart-swiss** [comment]
Debugging is a bit tricky because I would have to break policy at the workplace to run the apply on this outside of the CI/CD pipeline.

**Comment by jacobbednarz** [comment]
@upstart-swiss I really need the entire log as it also has the HTTP traffic which I can use to diagnose why this error isn't being handled by the error handler.

**Comment by upstart-swiss** [comment]
I'll see if I can modify our pipeline to save that error log.

If you want to test locally, this should generate the error:
```hcl
locals {
  big_ip_list = [ for i in range(1,254): "192.168.1.${i}"]
}

resource "cloudflare_zone_lockdown" "test_error" {
  zone_id     = "1234" # put yours here
  description = "generate_error"
  urls = [
    "*test.com*",
  ]

  dynamic "configurations" {
    for_each = local.big_ip_list
    content {
      target = "ip"
      value  = configurations.value
    }
  }

}
```

**Comment by jacobbednarz** [comment]
I've managed to replicate however I'm recieving an error as expected.

```
Error: error creating zone lockdown for zone ID "0da42c8d2132a9ddaf714f9e7c920711": error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"message\": \"zonelockdown.api.validation=max 250 IP/CIDRs exceeded\"\n    }\n  ],\n  \"messages\": []\n}\n"

  on terraform.tf line 57, in resource "cloudflare_zone_lockdown" "test_error":
  57: resource "cloudflare_zone_lockdown" "test_error" {
```

Is this what you're referring to? In the next release, we will have some improvements on the error output however it will still be the same content.

**Comment by jacobbednarz** [comment]
As I hinted at above, `stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"` is a red herring as it happens in loads of scenarios when the I/O is closed for the requests, not just errors.

**Comment by upstart-swiss** [comment]
Interesting, I don't get that error from Cloudflare when I make the change. I'll do some more testing on my side. I'll close this (since the `zonelockdown.api.validation=max 250 IP/CIDRs exceeded` is a completely acceptable error) and re-open when I have better steps to reproduce.
