### ISSUE TITLE
Cloudfare Provider Crashing: Panic

### ISSUE THREAD

**Issue by usrlocalang** [cloudflare/terraform-provider-cloudflare#991]
### Terraform version

0.13.6

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "public_dns_records" {
  for_each = var.cloudflare_map
  # this appears to be broken - the provider is returning a timestamp in zone_id instead of a zone_id. .
  # zone_id     = data.cloudflare_zones.REDACTED.id
  zone_id = "REDACTED"
  name    = each.key
  value   = each.value
  type    = "CNAME"
  ttl     = "1" # 1 == automatic
  proxied = true
}
...
```

### Panic output

2021-03-11T08:48:36.841-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 2021/03/11 08:48:36 [DEBUG] Data found in config: map[string]interface {}{}
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: panic: runtime error: invalid memory address or nil pointer dereference
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x103cdac]
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: goroutine 53 [running]:
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareRecordRead(0xc0004d4700, 0x13417c0, 0xc000564180, 0xc0004d4700, 0x0)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_record.go:442 +0xacc
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000190cf0, 0xc000108af0, 0x13417c0, 0xc000564180, 0xc0000cecc0, 0x0, 0x0)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:460 +0x129
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000e7c0, 0x1516240, 0xc000308600, 0xc0005526c0, 0xc00000e7c0, 0xc000308600, 0xc000698ba0)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x12fd8c0, 0xc00000e7c0, 0x1516240, 0xc000308600, 0xc000552660, 0x0, 0x1516240, 0xc000308600, 0xc000382200, 0x1e8)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c81c0, 0x1521a00, 0xc000093c80, 0xc00001c700, 0xc00025b1a0, 0x1c0c510, 0x0, 0x0, 0x0)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).handleStream(0xc0002c81c0, 0x1521a00, 0xc000093c80, 0xc00001c700, 0x0)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003e4210, 0xc0002c81c0, 0x1521a00, 0xc000093c80, 0xc00001c700)
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-11T08:48:36.843-0600 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021-03-11T08:48:36.845-0600 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/cloudflare/cloudflare/2.19.1/linux_amd64/terraform-provider-cloudflare_v2.19.1 pid=8545 error="exit status 2"
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [TRACE] [walkRefresh] Exiting eval tree: module.public_dns.cloudflare_record.public_dns_records["REDACTED-REDACTED--stage"]
2021/03/11 08:48:36 [ERROR] eval: *terraform.evalReadDataRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [TRACE] [walkRefresh] Exiting eval tree: module.public_dns.data.cloudflare_zones.REDACTED
2021/03/11 08:48:36 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/03/11 08:48:36 [TRACE] eval: *terraform.EvalSequence
2021/03/11 08:48:36 [TRACE] eval: *terraform.EvalGetProvider
2021/03/11 08:48:36 [TRACE] eval: *terraform.EvalSequence

### Expected output

To skip the creation of cloudfare if it exists or create it if it does not exist

### Actual output

Error: rpc error: code = Unavailable desc = transport is closing

### Steps to reproduce

terraform init
terraform plan

**Comment by ChristophShyper** [comment]
Duplicate https://github.com/cloudflare/terraform-provider-cloudflare/issues/988

**Comment by usrlocalang** [comment]
Problem solved.  Pin to 2.19.0
```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.19.0"
    }
  }
  required_version = ">= 0.13"
}

```
